### ISSUE TITLE
do not generate init design in mbo

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#104]
Provide a convenient helper to do this and always pass the design as a data frame.

I guess this is better design.

**Comment by jakob-r** [comment]
@berndbischl ping

**Comment by berndbischl** [comment]
@jakobbossek 
I am reviewing now, would you still do the necessary changes later, to finish this?

**Comment by berndbischl** [comment]
Review: 

1) The sanity checking should not be done here. But in mlrBO, maybe in checkStuff.

2) The logging of the points to the opt path should also not be done here, but in the beginning of mbo.

Otherwise I mean the code is nearly copy-paste from before, so I dont see what to review?

The general structure you posted seems ok. 

Here is the principle 

1) Either already have a df or call the new fun
2) pass the df to mbo
3) san check it
4) log to OptPath (and create internal objects if we need them)

**Comment by jakob-r** [comment]
I think it is a nice change especially for running experiments. 
@jakobbossek If you won't be able to do it in the next days pleas assign me.

**Comment by berndbischl** [comment]
I guess I will do this now to finalize it.

**Comment by jakob-r** [comment]
I think we can close, can't we? 
Convenience Wrapper seems unnecessary as it's just one PH call - which needs to be well documented.

**Comment by berndbischl** [comment]
I did this, we are done. 
@jakob-r 
Can you maybe add 2 lines of docs, and add a usual rox example to mbo?
then we can close

**Comment by jakobbossek** [comment]
What is the status here?

**Comment by berndbischl** [comment]
reread it please what i did and make sure that people know how to gen the design with PH from the docs.
then close

**Comment by jakobbossek** [comment]
Looks fine. Closing
