### ISSUE TITLE
plotExampleRun: plots not aligned

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlrMBO#109]
Same problem as decribed [here](http://stackoverflow.com/questions/22291088/adjusting-the-margin-space-for-axis-text-in-ggplot2) if we have very small numbers for the infill and ggplot switches to a scientific notation of the numbers on the y axis. The solution works for me, we should probably make it the default.

**Comment by jakobbossek** [comment]
This works well for two plots, but sometimes we have a 2x2 matrix of plots.

**Comment by jakobbossek** [comment]
We need to convert each plot into a gtable object, determine the maximal width of our plots and assign it to all others. I have already code for this. Looks great and works for arbitrary matrizes of plots.

**Comment by jakobbossek** [comment]
Argh. My solution works great for plots without facets, but messes it messes up with plot which use facetting :angry: 
However, to align the MBOResult plots we need to adapt the code in ParamHelpers.

**Comment by jakobbossek** [comment]
Well, I did not find a flexible, satisfactory solution for the problem until now.
* The solution Michel pointed to dows not work with facet plots
* My solution does not as well.

**Comment by jakobbossek** [comment]
Going to do this later. I think other issues are more important at the moment.

**Comment by berndbischl** [comment]
yo, guys, can we please post a reproducing example here, that we shows the problem?
so we can work against it?

**Comment by jakobbossek** [comment]
The following example constructs a set of ggplot objects we are frequently working with in ParamHelpers or mlrMBO. I have written some nice helpers and thought to have solved the alignment problem in a nice way. However, plots with facets need special care as it seems.

```splus
library(ggplot2)
library(grid)
library(gridExtra)
library(scales)

# Nice helper functions
# All expect a list of lists of ggplot objects and somehow transform these.
toGTable = function(pls) {
  lapply(pls, function(pl) {
    if (inherits(pl, "ggplot")) {
      return(ggplot_gtable(ggplot_build(pl)))
    }
    return(toGTable(pl))
  })
}

getMaxPlotWidth = function(pls) {
  do.call(unit.pmax, lapply(pls, function(pl) {
    if (!inherits(pl, "gtable")) {
      return(getMaxPlotWidth(pl))
    }
    return(pl$widths[2:3])
  }))
}


toAlignedGTable = function(pls, max.width) {
  lapply(pls, function(pl) {
    if (!inherits(pl, "gtable")) {
      return(toAlignedGTable(pl, max.width))
    }
    pl$widths[2:3] = max.width
    return(pl)
  })
}

# dummy data
data = data.frame(x = 1:100, y = runif(100), z = runif(100) * 100000, a = runif(100) * 10000000, b = sample(letters[1:2], 100, replace = TRUE))
pl1 = ggplot(data, aes(x = x, y = y)) + geom_point()
pl2 = ggplot(data, aes(x = x, y = z)) + geom_point()
pl3 = ggplot(data, aes(x = log(x))) + geom_histogram()

# we frequently have list of lists of ggplot objects
pls = list(list(pl1, pl2), pl3, pl1, pl2)

# 1) what we have until now (ugly unaligned plots!)
ppls = pls
ppls[[1]] = do.call(grid.arrange, c(ppls[[1]], nrow = 2))
do.call(grid.arrange, c(ppls, ncol = 2))

# 2) what we want (nice! Seems to work great!)
pls2 = toGTable(pls)
max.width = getMaxPlotWidth(pls2)
pls3 = toAlignedGTable(pls2, max.width)
pls3[[1]] = do.call(arrangeGrob, pls3[[1]])
do.call(grid.arrange, c(pls3, ncol = 2))

# 3) DAMN! add a facetted plot everything is messed up!
# Until now no solution found for this problem.
pls[[3]] = pls[[3]] + facet_grid(. ~ b)
pls2 = toGTable(pls)
max.width = getMaxPlotWidth(pls2)
pls3 = toAlignedGTable(pls2, max.width)
pls3[[1]] = do.call(arrangeGrob, pls3[[1]])
do.call(grid.arrange, c(pls3, ncol = 2))
```

**Comment by jakob-r** [comment]
Side remark: Do we really want to still do this in v0.1 as it seems not so easy?

**Comment by jakobbossek** [comment]
I think fixing this in a later version is ok.

**Comment by berndbischl** [comment]
100 % agree that fixing later is OK

**Comment by jakobbossek** [comment]
Well, we could simply assign a gorgerous left margin to each plot by default (this is easy). This would solve the problem. The only drawback is some more whitespace inbetween the plots. What is your opinion?

**Comment by jakob-r** [comment]
IMO: Do it, state clearly in the code how and where the margin is added, so that we can later find a more beautiful hack and still now what happens there.
But maybe before: Can you send a picture of how much white space we are talking about :wink: ?
But I don't want to be small minded on this topic anyway :smiley:

**Comment by jakobbossek** [comment]
Ok. Let's summarize:

* for 1D we use facetting and alignment is no problem
* for 2D each plot has the same axis labels / breaks and ticks. Hence no problem as well
* The alignment problem only occurs in `plot.MBOSingleObjResult` and `plot.MBOSingleObjResult` respectively and thus must be solved in ParamHelpers.

Going to close this here and open an issue in ParamHelpers.

By the way. Just realized: we make no use of faceting for the OptPath plots at all. Thus my solution should work fine.
