### ISSUE TITLE
Think about defaults for simple EA parameters.

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#11]

**Comment by jakobbossek** [comment]
Well, a default population size of 10 is quite small for >= 2D problems I guess. We could
* increase the default, but this is not the best solution IMHO
* set the default population size based on the number of parameters

I prefer the second approach.

**Comment by berndbischl** [comment]
just do it and doc it

**Comment by jakobbossek** [comment]
See PR #154

**Comment by jakobbossek** [comment]
Done

**Comment by berndbischl** [comment]
we can later deal with that as an ECR test case . with maybe self adaptation
