### ISSUE TITLE
allow internal scaling of numerical params to 0,1

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#127]

**Comment by berndbischl** [comment]
might increase model and optim stability

**Comment by jakob-r** [comment]
We might want to do this with a preprocWrapper from the mlr side?

**Comment by berndbischl** [comment]
i am not sure. 
it not only relates to the model, but also the initial design and the infill optimizer. 

well, i am not sure. i dont want to complicate this, we probably should dicuss whether we need this or not and how hard it is.

sorry, not the best possible "answer post"

**Comment by tobiaswagner** [comment]
I know I am no active developer, but here is my view. Feel free to think about it ;-)

If it is just about normalization, we should define it as standard. A normalization has many positive side effects:
- numerical stability
- comparison of the theta values
- ...
This standard normalization could be hided internally, the user always sees the original parameter values. Does anyone see some reason for defining a normalization as an option?

Is there already a solution for nonlinear transformations (rank, log, boxcox, etc.)? This would be something reasonable to have as an option.

Best regards
Tobias
________________________________________
Von: Bernd Bischl [notifications@github.com]
Gesendet: Montag, 4. Januar 2016 20:15
An: mlr-org/mlrMBO
Betreff: Re: [mlrMBO] allow internal scaling of numerical params to 0,1 (#127)

i am not sure.
it not only relates to the model, but also the initial design and the infill optimizer.

well, i am not sure. i dont want to complicate this, we probably should dicuss whether we need this or not and how hard it is.

sorry, not the best possible "answer post"

�

**Comment by berndbischl** [comment]
> I know I am no active developer, but here is my view. Feel free to think about it ;-)

Please continue providing valuable feedback.



> If it is just about normalization, we should define it as standard. 
> A normalization has many positive side effects:

Do you see any "downsides" to it? 


> This standard normalization could be hided internally, the user always sees the original parameter values. Does anyone see some reason for defining a normalization as an option?

Well, the way it is now, we always work on the original scale. And, as you are saying, we need to keep that to some degree to at least display at to the user, and store the orig scale in out OptPath object (= the archive).
So we need to put something "on top" of the current stuff at the moment anyhow. Which one could also disable, maybe to study the effect of the normalization.  If we introduce this, it would be "on" by default anyhow. 

Anyhow, whether an option exists to disable this normalization is maybe not such an important point.

> Is there already a solution for nonlinear transformations (rank, log, boxcox, etc.)? 
>This would be something reasonable to have as an option.

Actually, yes, we have stuff for this in place. 

We have:

a) X transformations, very generic ones, although they can only be applied to single univariate parameters, currently. 

Examples are 

par.set = makeParamSet(
  makeNumericParam("x1", lower=-10, upper=10, trafo = function(x) x^2),
  makeNumericParam("x2", lower=0, upper=1, trafo = function(x) 20*x - 10,
)

This ensures the following: The model and the optimizer we use internally "see" the params on the scale from lower to upper. The evaluated function sees the trafo'ed values. The optpath can be told to be logged on either scale. 
I personally have only used the trafo of x1, for params that should be optimized from 0 to +inf, so I often optimize on a log scale.
But "x2" does exactly what we want right? If we assume the orig. scale of "x2" is -10 to 10. 

This has 2 conclusions: We already support what we need, so the user is always free to write this down himself. Just a teeny bit inconvenient. And: We could easily add such transformation programmatically.

b) We have something for Y trafos, but this seems not really to be finished.

**Comment by tobiaswagner** [comment]
> Do you see any "downsides" to it?

Actually, no. In all my MATLAB codes for regression, this normalization is applied.

> Actually, yes, we have stuff for this in place.
> a) X transformations, very generic ones, although they can only be applied to single univariate parameters, currently.

This is great. What does univariate mean in this context? The transformations are only applied to single parameters in a separable fashion? I think this is no restriction, as transformations like Y1 = x1^2*x2^2 can be considered as features, not as transformations.

> makeNumericParam("x2", lower=0, upper=1, trafo = function(x) 20*x - 10)
> This ensures the following: The model and the optimizer we use internally "see" the params on the scale from lower to upper. The evaluated function sees the trafo'ed
> values. The optpath can be told to be logged on either scale. I personally have only used the trafo of x1, for params that should be optimized from 0 to +inf, so I often
> optimize on a log scale. But "x2" does exactly what we want right? If we assume the orig. scale of "x2" is -10 to 10.

I would agree, this looks even better than my realization in MATLAB, where I use the normalization only for the modelling and restrict to a linear transformation following  a few predefined transformations (log, sqrt). Your solution is much more flexible and the the normalization may also stabilize gradient computations during the internal optimization in case of very differently scaled parameters.

Best regards
Tobias
Von: Bernd Bischl [mailto:notifications@github.com]
Gesendet: Montag, 4. Januar 2016 23:52
An: mlr-org/mlrMBO <mlrMBO@noreply.github.com>
Cc: Tobias Wagner <wagner@isf.maschinenbau.uni-dortmund.de>
Betreff: Re: [mlrMBO] allow internal scaling of numerical params to 0,1 (#127)


I know I am no active developer, but here is my view. Feel free to think about it ;-)

Please continue providing valuable feedback.

If it is just about normalization, we should define it as standard.
A normalization has many positive side effects:

Do you see any "downsides" to it?

This standard normalization could be hided internally, the user always sees the original parameter values. Does anyone see some reason for defining a normalization as an option?

Well, the way it is now, we always work on the original scale. And, as you are saying, we need to keep that to some degree to at least display at to the user, and store the orig scale in out OptPath object (= the archive).
So we need to put something "on top" of the current stuff at the moment anyhow. Which one could also disable, maybe to study the effect of the normalization. If we introduce this, it would be "on" by default anyhow.

Anyhow, whether an option exists to disable this normalization is maybe not such an important point.

Is there already a solution for nonlinear transformations (rank, log, boxcox, etc.)?
This would be something reasonable to have as an option.

Actually, yes, we have stuff for this in place.

We have:

a) X transformations, very generic ones, although they can only be applied to single univariate parameters, currently.

Examples are

par.set = makeParamSet(
makeNumericParam("x1", lower=-10, upper=10, trafo = function(x) x^2),
makeNumericParam("x2", lower=0, upper=1, trafo = function(x) 20*x - 10,
)

This ensures the following: The model and the optimizer we use internally "see" the params on the scale from lower to upper. The evaluated function sees the trafo'ed values. The optpath can be told to be logged on either scale.
I personally have only used the trafo of x1, for params that should be optimized from 0 to +inf, so I often optimize on a log scale.
But "x2" does exactly what we want right? If we assume the orig. scale of "x2" is -10 to 10.

This has 2 conclusions: We already support what we need, so the user is always free to write this down himself. Just a teeny bit inconvenient. And: We could easily add such transformation programmatically.

b) We have something for Y trafos, but this seems not really to be finished.

**Comment by berndbischl** [comment]
Also not that the fitting of DiceKriging km is probably going to be faster if we do this internal scaling to 0,1

**Comment by jakob-r** [comment]
Just as a side note: I wrote this piece some time ago:
https://github.com/mlr-org/mlrMBO/blob/21b47d4d55bf856e287304b6139bd2913a6e0faf/R/TrafoWrapper.R

**Comment by berndbischl** [comment]
we should discuss whether this is the last thing we do in 0.1.
i will keep this in the milestone until then

**Comment by jakob-r** [comment]
I suggest, that we postpone that for a release after 0.1

**Comment by ja-thomas** [comment]
I ran some benchmarks on 5D testfunctions. At least for our default surrogate model. Results are not really conclusive for some problems it is slightly better or worse, runtime is increased by 3-5% on these functions.

**Comment by jakob-r** [comment]
Thanks for the benchmark. I removed the v0.1 milestone. Feel free to add it again ;)

**Comment by berndbischl** [comment]
@ja-thomas 
do you want to add the option to mlr, then close here? 
or simply throw the whole thing away? as it does not seem to do much?

**Comment by ja-thomas** [comment]
The code for km in mlr is basically done, but as it does not seem to help anything I don't think we need (and want) to merge it, I'll copy it to the ToDo files or something.

I would suggest that (sometime the future) we create an mlr wrapper similar to the Trafo wrapper jakob-r implemented. But that is definetly not for the first release.

**Comment by berndbischl** [comment]
ok then lets close here, and, yes do this: 


> don't think we need (and want) to merge it, I'll copy it to the ToDo files or something.
