### ISSUE TITLE
it should be better visible from the printer if we do random interleave evals

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#128]
this is a miny fix, but i got once confused when i looked at the console log and asked myself
"why are 2 point evaled, I only propose 1?"

**Comment by berndbischl** [comment]
really not that urgent. if one is not as stupid as I am, one can understand what goes on. 
also issue #149 should be fixed first, then this is easy.

**Comment by ja-thomas** [comment]
I think this is already done? Or am I overlooking something:

 random_interleave = 5
```
[mbo] 3: x=-3.23 : y = 19.3 : 0.0 secs : infill_ei
[mbo] 3: x=4.57 : y = 40 : 0.0 secs : random_interleave
[mbo] 3: x=-0.994 : y = 0.995 : 0.0 secs : random_interleave
[mbo] 3: x=5.01 : y = 25.1 : 0.0 secs : random_interleave
[mbo] 3: x=-2.72 : y = 19.4 : 0.0 secs : random_interleave
[mbo] 3: x=-1.65 : y = 18.7 : 0.0 secs : random_interleave
```

 random_interleave = 2
```
[mbo] 5: x=-1.5 : y = 22.3 : 0.0 secs : infill_ei
[mbo] 5: x=-1.09 : y = 2.8 : 0.0 secs : random_interleave
[mbo] 5: x=-4.96 : y = 24.9 : 0.0 secs : random_interleave
```

random_interleave = 0
```
[mbo] 5: x=2.25 : y = 14.8 : 0.0 secs : infill_ei
```


If so, we can close this.

**Comment by berndbischl** [comment]
ah yes. great.

**Comment by jakobbossek** [comment]
Yes, I added this a long time ago :-)
