### ISSUE TITLE
The whole control settings space should/could be a paramSet

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#129]
No text

**Comment by berndbischl** [comment]
?
no

**Comment by berndbischl** [comment]
why?

**Comment by jakob-r** [comment]
not so serious answer: so we can tune over it
serious anwer: so we can directly formulate dependecies of parameters and use the feasability check for the settings. Where is the difference of mbo settings and a setting for a learner in mlrMBO?

**Comment by berndbischl** [comment]
I dont know. I somehow can see your point. But I am not sure whether this is worth it.

First of all, the feasibility stuff is not helping much. As you do not get very expressive error msgs I think.
So you still want to do this manually with checkmate?

If it is doable, do a PR. 

But before you touch 1000 lines of code describe the structure of the changes first

**Comment by berndbischl** [comment]
dont want to do it now. 

if that EVER really bugs you in practice, just open again, in that case we can always talk
