### ISSUE TITLE
remove infill crit = random

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#130]
there is zero reason to have this clutter up the code and make our already complex project even more complex.

just consider these 2 points:

a) the interaction with the param "interleave"

b) is it correct that we now still fit models while in random search mode? 
and totally waste time?

conclusion: it was a very bad design decision to have that in the main loop!

**Comment by berndbischl** [comment]
@jakob-r

**Comment by jakob-r** [comment]
i will delete soon and investigate on a good solution

**Comment by berndbischl** [comment]
Let us please discuss first, then code.
Here, I think my personal preference is a clean separate implementation random search.
Input-Output should be as close to mbo as possible?

If you agree, post the API for that.

**Comment by jakob-r** [comment]
Okay. Then let's begin
I want to call exemplarly
```r
f = function(x) {...}
ps = makeParamSet(...)
ctrl = makeRSControl(
  minimize = ...,
  number.of.targets = ...,
  init.design.points = ...,
  init.design.fun = ...,
  init.design.args = ...,
  iters = ...,
  time.budget = ...,
  exec.time.budget = ...,
  target.fun.value = ...,
  final.evals = ...,
  y.name = ...,
  suppress.eval.errors = ...,
  save.on.disk.at = ...,
  save.on.disk.at.time = ...,
  save.file.path = ...,
  output.num.format = ...)

rs(fun = f, par.set = ps, design = NULL, control = ctrl, show.info = TRUE)
 ```

Not used arguments from `makeMBOControl`: 
* propose.points
* noisy
* final.method
* impute.y.fun
* trafo.y.fun
* store.model.at
* resample.at
* resample.desc
* on.learner.error
* show.learner.output

What could be an elegant solution to not have all these still necessary checks copy pasted?
```r
ctrl = makeOptimControl()
ctrl = setMBOControl(ctrl)
```
?

**Comment by berndbischl** [comment]
Why not, for now, simply use the normal control object, but ignore all settings in there during RS except for the ones that make sense? 
Later on we can better restrict this, but in order to move forward would do that now.

**Comment by berndbischl** [comment]
That also makes it very easy to reuse the helper functions that we already have and that operate on the control object?

**Comment by jakob-r** [comment]
I am fine with that approach.
