### ISSUE TITLE
Differentiate better between multipoint and multicrit

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#133]
currently it's kind of messed up. just have a look at the `setMBOControlMultiPoint` where a lot of multicrit stuff is set. Unfortunately I don't have the best insight in the whole Multicrit stuff. Help needed.

**Comment by danielhorn** [comment]
Uhm ... yes, of course multicrit stuff is set in multipoint? As in singlecrit it is possible to propose multiple points in multicrit. There are several different multicrit algorithms and for each algorithm one multipoint variant is implemented. The parameters of these multipoint variants are set in setMBOControlMultiPoint. We wrote a paper about this stuff.

Or do you want to introduce setMBOControlMultiCritMultiPoint?

**Comment by berndbischl** [comment]
There is some confusion going on. 
Let me try to help to clear this up.

Case A: We are in a single crit scenario. So f, the objective maps to R^1. 
The following multipoint methods are available

1) lcb
2) constant liar (cl)
3) multicrit 

3) is described in the MOIMBO paper. it uses MULTICRITERIA methods for a SINGLE CRIT scenario to propose MULTIPLE point. 

Case B: We are in a multicrit scenario. So f, the objective maps to R^k. 
The following methods are available
parego
dib
mspot

They can all handle 1-point proposal or multi-point-proposal.

The problem is actually, that NONE of these methods have parameters settable in setMBOMulticrit. 
So actually we dont possibly have too much multicrit stuff in there, maybe we have not enough.

First of all:
a) Does that info help?
b) How do we simplify things?

**Comment by berndbischl** [comment]
> There are several different multicrit algorithms and for each algorithm one multipoint variant 
> is implemented. The parameters of these multipoint variants are set in   . 

@danielhorn 
Are you sure this is correct? Which param setMBOControlMultiPoint is used in ANY multicrit method?

**Comment by danielhorn** [comment]
Hm ... I'm not sure ... I am a bit confused because of the prefix multipoint.multicrit. Ok, you are right, there are no parameters for our multipoint variants.

**Comment by berndbischl** [comment]
you mean this here right?

```
#' @param multicrit.maxit [\code{character(1)}]\cr
#'   Number of generations for multicriteria EA.
#'   Default is 100.
#' @param multicrit.sbx.eta [\code{numeric(1)}]\cr
#'   Distance parameter of crossover distribution, see \code{\link[emoa]{sbx_operator}}.
#'   Default is 15.
#' @param multicrit.sbx.p [\code{numeric(1)}]\cr
#'   Probability of 1-point crossover, see \code{\link[emoa]{sbx_operator}}.
#'   Default is 1.
#' @param multicrit.pm.eta [\code{numeric(1)}]\cr
#'   Distance parameter of mutation distribution, see \code{\link[emoa]{pm_operator}}.
#'   Default is 15.
#' @param multicrit.pm.p [\code{numeric(1)}]\cr
#'   Probability of 1-point mutation, see \code{\link[emoa]{pm_operator}}.
#'   Default is 1.
```

these are all MOIMBO params I think. And the "multcrit." prefix name then sucks.
(this was introduced before MBO even handled multicrit scenarios)

Shall we rename this? and improve the docs in general?

**Comment by danielhorn** [comment]
I was just posting about renaming it ;)

Perhaps we should stop using the term "multicrit" for both MOO and the multipoint method? Of course, it is both multicrit. But it is really confusing to have the same name for 2 completely different things.

If it is MOIMBO, let's call it MOIMBO?

**Comment by danielhorn** [comment]
So, for example, moimbo.maxit, moimbo.sbx.eta

**Comment by berndbischl** [comment]
> So, for example, moimbo.maxit, moimbo.sbx.eta

Yup, exactly my idea. But we should also iterate over setMBOControlMultiPoint and setMBOControlMulticrit and check whether it is REALLY clear how multipoint works.
And random interleave is also some kind of multipoint or?
(I kinda hate that option)

**Comment by jakob-r** [comment]
Thanks for clearing me up. Improving these setters and their documentation is much appreciated :+1:

>Or do you want to introduce setMBOControlMultiCritMultiPoint?

Sounds about right :smile:

**Comment by berndbischl** [comment]
> setMBOControlMultiCritMultiPoint?

But what should go in there?

**Comment by berndbischl** [comment]
IMHO we should make the docs clearer and rename:


multicrit.maxit, multicrit.sbx.eta -->
moimbo.maxit, moimbo.sbx.eta

and so on.

**Comment by jakobbossek** [comment]
> IMHO we should make the docs clearer and rename:

> multicrit.maxit, multicrit.sbx.eta -->
> moimbo.maxit, moimbo.sbx.eta

Or even get rid of these special parameters, since we can reuse `opt.ea.maxit`, `opt.ea.sbx.eta`, ...

**Comment by jakobbossek** [comment]
See #77
