### ISSUE TITLE
plotMBOResult broke in ParamHelpers or ggplot2 2.0 ?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#134]
It doesn't work anymore and the tests will fail. Even if I check out an older version.

**Comment by berndbischl** [comment]
ggplot2 has had an API change in version 2.0.
we also had to change mlr for this.

**Comment by berndbischl** [comment]
can you please look at this and see what needs to be changed?
@larskotthoff also did this for mlr, so maybe ask him.
but first look at his commit diff for mlr

**Comment by larskotthoff** [comment]
For mlr the changes were really only that some of the colours are very slightly different now (which only affected the mlr testing) and that there's no `vjust` argument for labels(?) anymore.

**Comment by berndbischl** [comment]
Thats why I hope it is simple to fix it here now, too....

**Comment by jakob-r** [comment]
I somehow have my doubts that it has something to do with ggplot2 seeing the error message but i will investigate.

**Comment by jakob-r** [comment]
Found the root of the problem: https://github.com/ggobi/ggally/pull/128

**Comment by jakob-r** [comment]
More detail: we try to add a `scale_colour_manual` to value we expect to be factor which is unexpectedly converted to numeric by GGally

**Comment by jakob-r** [comment]
GGally is updated, now everything works again
