### ISSUE TITLE
Force to pass smoof functions?

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#140]
The [smoof package](http://www.github.com/jakobbossek/smoof) allows for the creation of functions with continuous-only or mixed parameter spaces.
@berndbischl: I think we talked about that shortly already about a year ago. What about forcing the objective functions to be of type `smoof_function`. I think this way we would unclutter the mbo interface a bit (since `par.set`, `noisy`, ... are properties of the smoof function at hand). Moreover, we might take benefit form smoofs plotting functions to unclutter the exampleRun stuff.

**Comment by berndbischl** [comment]
OK. If you take this over and document it, I agree that this might be good.
Would you do a PR?

**Comment by jakobbossek** [comment]
Yes, I will take care of this.

**Comment by jakobbossek** [comment]
Started to work on it. There are some points we should discuss:
* [smoof functions](http://www.github.com/jakobbossek/smoof) have a lot of properties/attributes, e.g., noisy, minimize, n.objectives. Currently we pass the aforementioned stuff to the control object by hand.
There are two possibilities now:
1. Remove all those parameters from the control object interface and assign them internally based on the passed smoof function inside mbo. Well, this is not going to work well, since makeMBOControl already does a lot of checks on, e.g., target.fun.value. This is why I favor option 2)
2. Let the user pass the smoof function as a parameter to the control object. The control object could extract all the neccessary information from the function itself. However, this way the use has to has the function to the control object and to mbo as well, which is kind of bad design.

Other suggestions are welcome.

**Comment by berndbischl** [comment]
I dont get it? Why not simply remove all the properties from the control object and simply, only use smoof? without any further internal assignment?

**Comment by jakobbossek** [comment]
I can remove all the properties from the control object which are also properties of a smoof function. But the control object also sets for instance `y.name` which depends on the number of objectives, which is - if removed - not available in the control object generator anymore.

**Comment by berndbischl** [comment]
But where is the problem to then leave y.name in the control? 
Please note that the function "checkStuff" already exists as many thinks have to be checked when mbo is called and "all info is there, together". Just move the arg check to that place?

**Comment by jakobbossek** [comment]
Ah, yes. Ok.

**Comment by berndbischl** [comment]
But PLEASE.

Before you do that. Post a call example here, with a simple userdefined math function, how on the new system mbo would be called.

**Comment by jakobbossek** [comment]
```splus
obj.fun = makeSingleObjectiveFunction(
  name = "Mixed decision space function",
  fn = function(x) {
    if (x$foo == "a") {
      return(5 + x$bar^2 + rnorm(1))
    } else if (x$foo == "b") {
      return(4 + x$bar^2 + rnorm(1, sd = 0.5))
    } else {
      return(3 + x$bar^2 + rnorm(1, sd = 1))
    }
  },
  par.set = makeParamSet(
    makeDiscreteParam("foo", values = letters[1:3]),
    makeNumericParam("bar", lower = -5, upper = 5)
  ),
  has.simple.signature = FALSE, # function expects a named list of parameter values
  noisy = TRUE
)

ctrl = makeMBOControl(init.design.points = 20L, iters = 10L)

# we can basically do an exhaustive search in 3 values
ctrl = setMBOControlInfill(ctrl, crit = "ei",
  opt.restarts = 1L, opt.focussearch.points = 3L, opt.focussearch.maxit = 1L)

lrn = makeLearner("regr.randomForest", predict.type = "se")

run = exampleRun(obj.fun, learner = lrn, control = ctrl,
	points.per.dim = 50L, show.info = TRUE)
```

**Comment by berndbischl** [comment]
Can I simply omit the name? And what are the defaults for the last 2 flags?

**Comment by jakobbossek** [comment]
The name is mandatory at the moment, but I already planned to make it optional. `noisy` is `FALSE`  and `has.simple.signature` is `TRUE` by default.

**Comment by jakobbossek** [comment]
Internally each smoof function has a *non-simple siganature*. However, if `has.simple.signature` is `TRUE`, an unlist wrapper similar to `makeMBOFunction` is applied.

**Comment by berndbischl** [comment]
so this would be valid then?

```

obj.fun = makeSingleObjectiveFunction(
  fn = function(x) sum(x^2)
  },
  par.set = makeNumericParamSet(len = 3, lower = 0, upper = 1)
}

```

**Comment by jakobbossek** [comment]
Yup

**Comment by berndbischl** [comment]
then go, do it

**Comment by jakobbossek** [comment]
We need to talk about the control stuff again. There is quite a lot information that depends on the properties I would remove from control. If you print the control object before applying mbo occasionally you will get faulty information, since the corresponding check could not be accomplished.
For instance the following stuff is part of `makeMBOControl`:

```splus
  if (number.of.targets == 1L && propose.points > 1L)
    control = setMBOControlMultiPoint(control)
  if (number.of.targets > 1L)
    control = setMBOControlMultiCrit(control)
```

Moreover we print a lot of stuff in `print.MBOControl`:

```splus
catf("Objectives                    : %s", collapsef("%s = %s!", x$y.name, ifelse(x$minimize, "min", "max"), sep = "; "))
catf("Function type                 : %s",  ifelse(x$noisy, "noisy", "deterministic"))
...
```
We cannot print this information, if we do not pass the objective fun to `makeMBOControl`.

**Comment by berndbischl** [comment]
The fix for the printer is easy: As this is not part of the control anymore, and smoof probably has a printer, remove it.

The rest above is basically ensuring correct "default" settings. It must be possible to just slightly change this, right? And do this otherwise?

**Comment by jakobbossek** [comment]
Work in progress. Unfortunately this is a lot of monkey work.
Going to finish at the beginning of the next week.

**Comment by jakobbossek** [comment]
I would like the user to at least pass the `number.of.targets` to `makeMBOControl`. Otherwise setting the defaults is complicated and correct information cannot be printed by the printer. For instance if our objective functions is multi-objective and we want to stick to the default mbo settings for multicrit methods, the control printer cannot give any information on that, since the number of targets is unknown.

```splus
fn = makeZDT1Function(dimensions = 2L)
...
ctrl = makeMBOControl(...)
print(ctrl) # no output regarding the used multicrit method possible
```

**Comment by berndbischl** [comment]
I dunno, can we not try to keep it simple and well-defined?
Just force the user to enable multicrit via setMBOMulticrit. He is likely to do that anyhow to change a setting, like the method.

Then you know he touched that, and you can use that in the printer?

**Comment by jakobbossek** [comment]
Well, I think it is still simple and well-defined. Moreover our clean and clear internal structure remains as is. Besides, I think it is quite intuitive, that the control object needs to know about some characteristics of the objective function.

**Comment by berndbischl** [comment]
Ok. I am fine with that too.
