### ISSUE TITLE
add "type" col to optpath that defines how the point was proposed

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#149]

**Comment by berndbischl** [comment]
at the moment we have at least

- the infill crit (use name string here)
- random interleave
- dunno, random generation of point when model broke?

**Comment by berndbischl** [comment]
not that urgent, can be done later

**Comment by jakobbossek** [comment]
Working on that and #128.
One stupid question. What is the type, e.g., of points proposed by parEGO?
Is it `parEGO` or the name of the `infill.crit` used internally by `proposePointsParEGO`?
Maybe best concatenate and set the type to `parEgo.ei` if expected improvement was used.

**Comment by jakobbossek** [comment]
#128 depends on that. Thus, i changed the milestone and label.

**Comment by jakobbossek** [comment]
Nearly finished. Just waiting for your answer.

**Comment by berndbischl** [comment]
I would suggest to have a SIMPLE list of types that we can later extend. And we should define it here first. Can you post what types you currently have?

**Comment by jakobbossek** [comment]
Currently we have:
* infill crit names, i.e., `mean`, `se`, `ei`, `aei`, `cb`, `eqi`, `dib`, `multiFid` 
* `random (interleave)` for points randomly inserted if (`interleave.random.points` > 0)
* `random (filtered)` for points which are replaced by random if filtering is active

**Comment by jakobbossek** [comment]
ping

**Comment by berndbischl** [comment]
I propose this list of names, which makes it easier to determine subgroups:

mean, se, ei, aei, cb, eqi, dib, multiFid --> add "infill_<crit>" as a prefix and use "multfid"  (all lower case)
+
random_interleave
random_filtered
+
initdesign

that covers all?

**Comment by jakobbossek** [comment]
I think so.

**Comment by berndbischl** [comment]
then go

**Comment by jakobbossek** [comment]
Ok. We forgot MOIMBO. I am not familiar with the multi-objective mbo stuff. Do we optimize two infill criteria simultaneously in this case?

**Comment by berndbischl** [comment]
Just call infill_moimbo in all cases

**Comment by mllg** [comment]
Fixed via #189.
