### ISSUE TITLE
check that it is documented how the "error imputation" / errorhandling in evalTargetfunction works

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#152]

**Comment by berndbischl** [comment]
also note that i removed configuremlr from mbo interface

**Comment by danielhorn** [comment]
This is documented in doc_error_handling.R and in makeMBOControl, and I think the documentation is sufficient. Okay, you have to read both help-pages to fully understand it

**Comment by jakob-r** [comment]
Can we close @berndbischl ?

**Comment by jakobbossek** [comment]
@berndbischl ping
