### ISSUE TITLE
check that current paralleization is documented

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#161]

**Comment by berndbischl** [comment]
also please dont close this, i want to pair-review this

**Comment by berndbischl** [comment]
@jakob-r 
also note that in your PR you added a new level that you did not register in zzz.....

please test that also locally

**Comment by jakob-r** [comment]
I think we are done here

**Comment by berndbischl** [comment]
> also please dont close this, i want to pair-review this

please do read at least the thread...

**Comment by jakob-r** [comment]
okay - you added it to zzz - but maybe i didn't get what you mean by "test locally"

**Comment by berndbischl** [comment]
I mainly meant that we should again at least with 4 eyes look at the current state, and discuss it. Before we close.

**Comment by berndbischl** [comment]
we agreed: 
- remove level true.feval.
- bb iterates doc_mbo_parallel

**Comment by jakob-r** [comment]
Should be done with PR #179. So @berndbischl is left with
* bb iterates doc_mbo_parallel

**Comment by jakob-r** [comment]
ping @berndbischl

**Comment by jakobbossek** [comment]
ping @berndbischl

**Comment by jakobbossek** [comment]
The docs are satisfying IMHO.

**Comment by jakob-r** [comment]
@berndbischl Will close tomorrow if you do not respond :wink:

**Comment by jakobbossek** [comment]
@jakob-r Please close. Tomorrow already passed some time ago 😋
