### ISSUE TITLE
the shouldTerminate function need to be refactored

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#167]
it is a bit strange.
we have some codes in there. these codes are then mapped to string.

- the function is pretty undocumented

- why do we first return codes, then map them to strings with an extra function?
why not simply return a bool flag "is.terminated" and a string "reason"

**Comment by jakobbossek** [comment]
shouldTerminate should just return the return value of the satisfied stopping condition IMHO. I.e. a list with the bool flag, a character string with the stop message and the "reason". This way we can omit the mapping entirely.

**Comment by jakobbossek** [comment]
We should drop the codes. My proposal:
Each stopping condition should return three things:
* user friendly/readable message
* logical value indicating whether the stopping condition is met
* the state as a short string
This way we skip the tedious mapping of codes to states. The latter should be optional for custom stopping conditions. In this case we set the state manually to `manual.exceeded`.

**Comment by jakob-r** [comment]
@jakobbossek +1
Who will do it? ;)

**Comment by jakobbossek** [comment]
I worked on the refactoring already. Thus I will continue working on it ;-)
@berndbischl: what is your opinion on my proposal?

**Comment by jakobbossek** [comment]
ping

**Comment by berndbischl** [comment]
@jakobbossek 
I agree with what you said, go ahead.
I it would be great if #187 is fixed at the same time

**Comment by jakobbossek** [comment]
Ok. Going to do this tomorrow.

**Comment by jakobbossek** [comment]
Please review PR #188

**Comment by berndbischl** [comment]
done
