### ISSUE TITLE
setSeed at loadOptState

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#181]
We had this
https://github.com/mlr-org/mlrMBO/commit/5d5a0d853c145aa8460905632fa9edbda7fef133#diff-438fe61749bde9a3264e60a23b88e090L100
which was not working and thus deleted.
Maybe we want to integrate it like this:
https://github.com/mllg/batchtools/blob/master/R/seed.r

**Comment by berndbischl** [comment]
as michel did this in bt, it is probably best when he also fixes this here. 
the seeding is important, we should not fuck this up, so added to MS 0.1
