### ISSUE TITLE
doc MBOResult$final.state

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#187]
what strings are possible, if it is a fixed set of constants

**Comment by berndbischl** [comment]
we also need to be sure that it is clear what these values mean. maybe put them on one page and only link to this.

**Comment by berndbischl** [comment]
doc all of these on the makeMBOTermination page. probably in a small table. 
also make cleanr what the difference between time and exec.time is (yes I know this)
the meanings itself are otherwise pretty clear from the page.

and rename them. the current names are bad.
do this:

term.exectime
term.time
term.feval
term.yval
term.custom

The arg names should exactly match these, but without the "term."

**Comment by jakobbossek** [comment]
Added documentation of final.state to MBOResult docs.
PR is coming soon. Just waiting for the checks to pass.

**Comment by jakobbossek** [comment]
Please review PR #188
