### ISSUE TITLE
Give the user access to the OptState object

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlrMBO#198]
I would find it useful if `mbo` were to return the OptState object (maybe when a flag is set), instead of only the MBOResult. Similarly, make `mboContinue` accept an OptState object (or just export `mboTemplate`) and export the OptState_getter.R functions -- this would also be helpful when defining a custom termination function via `setMBOControlTermination(more.stop.conds=...)`.

**Comment by jakob-r** [comment]
We are currently in a phase of heavy development and many changes and we can not guarantee that those internals will stay consistent and as a consequence we don't want that anyone believes that he can safely build upon that structure nor do we have the resources to document everything so detailed that we feel save to export it. 

It is on my internal to-do list to restructure the mboResult - i just kept it the old way when I introduced the OptState thingy - to stay compatible. As I feel that you have a lot of developerish ambitions feel free to access everything using `mlrMBO:::` and also let me know what you feel could be better in the internal structure.

Hint: As you might have already found out: `final.opt.state = mlrMBO:::mboTemplate(opt.state); res = mlrMBO:::mboFinalize2(final.opt.state)` is basically what you are looking for when you ask for `mboContinue`. 

If you don't concour I will close this issue.

**Comment by mb706** [comment]
Believe me, I do use `:::` a lot ;-)
I feel like having some kind of state object that one can use to continue a run (e.g. after reconsidering the termination criteria, or to save progress as part of another data structure instead of on disk) without having to resort to the file system [or other trickery](https://github.com/mlr-org/automlr/blob/10e3d8be51daa5d8e1940ffdf11a18bad9a63cf2/R/optMBO.R#L59-L62) would be useful, even if the object would need to be treated as a black box.
Of course you have to consider the project's priorities, so feel free to close / mark as wontfix as you see fit.

**Comment by jakob-r** [comment]
Interesting hack :smile: I will push the restructuring of the mbo result a bit forward in my head.

**Comment by mb706** [comment]
Closed by #362
