### ISSUE TITLE
checkLearner returns regr.km learner even if par.set contains logical parameters

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlrMBO#204]
Because [this](https://github.com/mlr-org/mlrMBO/blob/7ca9ad456e18024f8d1d1cacfe8f1a3ad3a67360/R/checkLearner.R#L19) doesn't look for logical parameters. Since logical parameters seem to be treated elsewhere (e.g. the [end of infillOptFocus.R](https://github.com/mlr-org/mlrMBO/blob/7ca9ad456e18024f8d1d1cacfe8f1a3ad3a67360/R/infillOptFocus.R#L77)), I assume that mlrMBO is _supposed_ to handle them?

**Comment by jakob-r** [comment]
Fixed in #216
