### ISSUE TITLE
Defaults for Terminations criterions

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#210]
I made this error - I think other people would to. I used:

`control = setMBOControlTermination(control, max.evals =  300)`

And for some curious reason MBO with this setting was worse than random search. The reason:  iters has an default value of just 10 iterations. So MBO stopped after 10 iterations, making only 30 f.evals, instead for 300.

I don't think 10 is a useful default for iters, probably NULL and forcing the user to set at least one termination criterion would be better.

**Comment by danielhorn** [comment]
Even better, with my fixed code I get this error:
```
Error occurred: Error in setMBOControlTermination(control, max.evals =300, iters = NULL) : 
  You need to specify a maximal number of iteration, a time budget or at least
      one custom stopping condition, but you provided neither.
```

**Comment by jakob-r** [comment]
That should definitely be improved. I will look into it now and make a proposal.

**Comment by jakob-r** [comment]
Discussion in #212
