### ISSUE TITLE
Standard MBO Codes

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlrMBO#211]
Hi,

are there standard mlrmbo-Codes available e.g. for some standard classification algorithms like randomForest, adaBoost or SVM? 
If not, I think that would be cool at least for the tutorial.

**Comment by danielhorn** [comment]
Hi Philipp,

there are some standard examples in inst/expamples. But they are for artificial optimization functions only. If you want to tune an svm, you have to build your target function, e.g. the accuarcy of the svm for a given parameter setting, yourself. Or I can send you some of my own code and you can build an official example from it?

**Comment by PhilippPro** [comment]
Why not, I can try it, although my experience with SVM is not very vast until now, so I do not know what parameters should be tuned and in what space. 
Target function could be build with standardized mlr interface, I think, so it is generalisable.

**Comment by jakob-r** [comment]
We have a unexported method to use mlrMBO for hyperparameter optimization in mlr. You can see how it works here:
https://github.com/mlr-org/mlr/blob/master/tests/testthat/test_tune_tuneMBO.R

**Comment by PhilippPro** [comment]
Ok, thanks, that is also helpful.

**Comment by PhilippPro** [comment]
One remark: In random forest (or in any algorithm that uses bagging) out of bag predictions could potentially be used for tuning (and thus making it much faster than with resampling).

**Comment by jakob-r** [comment]
You are always free to code your own objective function :wink: The function is just the most generic solution. But anything related to hyperparameter optimization might be more relevant in mlr than here.

**Comment by PhilippPro** [comment]
Ok.

Here just an example how I used it for optimizing random forest, using the oob-predictions. 
It is not very clear to me, how to set the hyperparameter values of focussearch or parego, but maybe I should read something about this. ;)

I think sample.fraction and replace are the most important hyperparameters in this case.

```
library(mlrMBO)
library(mlr)

# Define the regression task
data(airquality)
# delete NA values
airquality = airquality[!apply(is.na(airquality),1, function(x) any(x) ),]

# Define our target function
# Measures: MSE
performan = function(x)  {
  pred <- ranger(formula = Ozone ~ . , data = airquality, sample.fraction = x$sample.fraction, replace = x$replace, 
                 num.trees = 10000)$predictions
  measureMSE(airquality, pred)
}

# Its ParamSet
ps = makeParamSet(
  makeLogicalParam("replace"),
  makeNumericParam("sample.fraction", lower = 0.05, upper = 1),
  makeDiscreteParam("min.node.size", values = 1:10),
  makeDiscreteParam("mtry", values = 1:5)
)

# Budget
f.evals = 40
mbo.init.design.size = 30

# Focus search
infill.opt = "focussearch"
mbo.focussearch.points = 100
mbo.focussearch.maxit = 3
mbo.focussearch.restarts = 3

# The MLR Learner
classif.lrn = makeLearner("classif.ranger", predict.type = "response")

library(mlrMBO)
# The final SMOOF objective function
objFun = makeMultiObjectiveFunction(
  name = "reg",
  fn = performan,
  par.set = ps,
  has.simple.signature = FALSE,
  noisy = TRUE,
  n.objectives = 1,
  minimize = c(TRUE)
)

# Build the control object
method = "parego"
if (method == "parego") {
  mbo.prop.points = 10
  mbo.crit = "cb"
  parego.crit.cb.pi = 0.5
}

control = makeMBOControl(n.objectives = 1L, propose.points = mbo.prop.points)
control = setMBOControlTermination(control, max.evals =  f.evals, iters = 300)
control = setMBOControlInfill(control, crit = mbo.crit, opt = infill.opt,
                              opt.focussearch.maxit = mbo.focussearch.maxit,
                              opt.focussearch.points = mbo.focussearch.points,
                              opt.restarts = mbo.focussearch.restarts,
                              crit.cb.pi = parego.crit.cb.pi, crit.cb.lambda = NULL)

mbo.learner = makeLearner("regr.randomForest", predict.type = "se")

design = generateDesign(mbo.init.design.size, smoof::getParamSet(objFun), fun = lhs::maximinLHS)

set.seed(123)
result = mbo(fun = objFun, design = design, learner = mbo.learner, control = control)
```

**Comment by jakob-r** [comment]
parego is the parallel version which evaluates more then one point per mbo iteration. you might want to use `parallelMap::parallelStartMulticore(level = "mlrMBO.feval")` to make use of it if you have a Linux system or other `parallelStart*` functions.

**Comment by danielhorn** [comment]
ParEGO is the multi-objective version ;) Since you set n.objectives = 1L, you are not using ParEGO, but normal EGO.

**Comment by PhilippPro** [comment]
One EGO is enough for me. ;)

**Comment by jakob-r** [comment]
See edit.

**Comment by berndbischl** [comment]
> One remark: In random forest (or in any algorithm that uses bagging) out of bag predictions could potentially be used for tuning (and thus making it much faster than with resampling).

Read this here:

https://github.com/mlr-org/mlr/issues/338
Would be great if you could help with this.


Can we close this issue here? Are all questions answered?

**Comment by PhilippPro** [comment]
yes.
