### ISSUE TITLE
Should we by-default store predicted.y in opt.path?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#214]
I wonder why we aren't doing it.

**Comment by berndbischl** [comment]
We are storing only the infill crit at the moment. but we can of course add this. do a PR?

**Comment by berndbischl** [comment]
for me it seem reasonable to have this as well.

**Comment by jakob-r** [comment]
That we can do this is out of question :wink: I will look into it. I just see some struggle with multicriteria maybe.

**Comment by berndbischl** [comment]
> I will look into it. I just see some struggle with multicriteria maybe.

but we handle infill crits there as well? and "mean" can be an infill crit. 
either do it the same way, or if not possible, document properly that it is left out (or NA)

**Comment by jakob-r** [comment]
Further thinking also brought me to the conclusion that it might be a good idea to store additional information based on the chosen infill-criteria. One simple solution would be to add the components of the infill criteria in the attributes of each infill-result so you can always see what terms lead to the specific value. For example
```r
infillCritEI = function(points, models, control, par.set, design, iter) {
#...
  p = predict(model, newdata = points)$data
#...
  ei = d * xcr.prob + p.se * xcr.dens
#...
  res = ifelse(p.se < 1e-6, 0, -ei)
  attr(res, "se") = p$se
  attr(res, "mean") = p$response
}
```

**Comment by jakob-r** [comment]
Discussion in #215
