### ISSUE TITLE
Documentation manpages

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#217]
We have to adapt the documentation to the new api-changes urgently. Many people already got confused.
Here are some notes in german by @Dotterbart
## 1.

> exampleRun(): 
> 
> Beschreibung deutet darauf hin, dass hier durch einen anschaulichen Durchlauf das Verfahren visualisiert wird.
> In der Hilfe wird nicht sofort klar, wie die Funktion beschaffen sein sollte.
> Vermutlich sollte in der Parameterbeschreibung bei der Funktion stehen, dass es eine smoof_single_objective_function sein sollte. 
> (Was ist und )Wie erhält man eine smoof_single_objective_function?
> Beispiel zur Funktionsnutzung wäre hilfreich.
> Die Nutzung hat bei mir zunächst auch nicht geklappt:
> 
> ``` r
> > def.cont = makeMBOControl()
> > foo = makeSingleObjectiveFunction(fn = function(x) x[1]^2 + x[2]^2 + sin(x[1]/(x[2]+2)),
>                                  par.set = makeNumericParamSet("x", len = 2, lower = -1, upper = 1))
> > exampleRun(foo, control = def.cont) 
> # Error in if (control$noisy) { : argument is of length zero
> > traceback()
> # 2: checkLearner(learner, par.set, control)
> # 1: exampleRun(foo, control = def.cont)
> ```
## 2.

> mbo(): 
> 
> Vermutlich sollte in der Hilfe in der Parameterbeschreibung der Funktion stehen, dass es sich um eine smoof-Datei handeln muss.  
> (Was ist und )Wie erhält man eine smoof_function?
> Im von Dir eingefügten Beispiel wird kein `name` angegeben, obwohl hier kein default besteht, daher wirft das Beispiel einen Fehler.
> Was plot.MBOSingleObjectResult() liefert, ist für mich nicht nachvollziehbar, hab jedoch auch wenig Ahnung von dem angewendeten Verfahren.
## 3.

> setMBOControl():
> Hilfe wirkt hier auf den ersten Blick klar, ich hab hier aber auch nicht wirklich rumprobiert, da ich dafür mit dem Verfahren nicht vertraut genug bin.
> 
> Mehr oder weniger random angeschaute Sachen:
## 4.

> makeMBOTrafoFunction():
> In der Hilfe steht, dass es eine Transformationsfunktion für MBOExampleRun erstellt. Mit exampleRun(TrafoFun) ist jedoch der Funktionstyp falsch (vermutlich nicht so gemeint...). 
> [später] Nach etwas Nachlesen gehe ich jetzt davon aus, dass damit eine Funktion erstellt wird, die für das MBOControl-Objekt einer Ausführung von exampleRun(fun, control = ...) genutzt wird.
## 5.

> mbo_parallel:
> Mit parallelMap bin ich nicht wirklich gut vertraut. Ich verstehe das so, dass die beiden genannten Level (mlrMBO.feval und mlrMBO.propose.points) in parallelStart() als solche angegeben werden können.
> Ganz klar ist mir dann aber noch nicht, wie die parallele Berechnung angestossen wird, das "Internally" in der Hilfe zu mbo_parallel deutet nach meinem Verständnis darauf hin, dass eine mlrMBO-Funktion genutzt wird und diese intern auf parallelMap zugreift.
> Ich wüsste allerdings nicht, welche der Funtionen aus der internen Dokumentation das dann sein sollte.
## 6.

> Bei Ausführung von mbo() mit der AckleyFunktion aus `smoof` kommt es zur Fehlermeldung:
> 
> ``` r
> # Error in requirePackages(package, why = paste("learner", id), default.method = "load") : 
> # For learner regr.km please install the following packages: DiceKriging
> ```
> 
> DiceKriging steht in der Description unter den suggests.
> 
> Das gleiche gilt für die packages GGally und akima beim Aufruf von plot(res.mbo), auch sie werden nicht automatisch installiert und es entsteht eine Fehlermeldung, wenn der Nutzer sie nicht schon vorher installiert hatte.
> Ich vermute, dass das gemäß Hilfe zu mbo_default_learner auch für das Paket randomForest gilt, falls dieses getriggerrt wird.

**Comment by berndbischl** [comment]
ich schreibe mal auf deutsch weiter weil sowieso alles auf deutsch hier ist.
@jakob-r @ja-thomas 

diese thread sind "schlimm" weil sie nie ganz fertig werden. lasst uns das also möglichst fix machen.
die meisten dinge sind trivial hier. wie regeln wir das?

**Comment by ja-thomas** [comment]
Um das ganze etwas konkreter zu machen, statt dem Text eine Stichpunkt Liste:

- [x] Function should be `singeObjectiveFunction` in `mbo` and `exampleRun` (inherits params from mbo)
- [ ]  Description of `plot.MBOSingleObjResult`

 `plot.MBOSingleObjResult` is using plotOptPath from paramHelpers and the manpage there is detailed. I think this is ok.

- [ ] `makeMBOTrafoFunction` not only for `MBOExampleRun` but for `mbo` as well. Actually for 'makeMBOControl' to be precise.

This is one line, I can make a PR, but maybe @jakob-r can fix it directly since I cannot push to the repo.

- [ ] `mbo_parallel` is unclear 

Should we just link to the tutorial part (when it's done)? If so we can check

Any additional points?

As far as I tested around with the package the manpages seem to fit to the functions. But we need more examples.

**Comment by jakob-r** [comment]
2) Agree. Maybe one sentence "This function uses
#' \code{\link[ParamHelpers]{plotOptPath}} from package \code{ParamHelpers}." See there to understand what you see"

4) I have yet to be sure if I want this function im MBO as this should be more a subject to smoof or the user of MBO.

**Comment by berndbischl** [comment]
> This is one line, I can make a PR, but maybe @jakob-r can fix it directly since I cannot push to the repo.

@ja-thomas seems to have rights now. otrherwise please complain.

**Comment by ja-thomas** [comment]
Except for 4) everything seems to be done here. This is just one line I'll push this small documentation to master and we can close here.

There is still the manpages branch which has some a lot of conflicts with master in regards of documentation. I'm not sure what is more up to date.

**Comment by jakob-r** [comment]
Regarding the manpages branch. It should be already merged: https://github.com/mlr-org/mlrMBO/pull/229
