### ISSUE TITLE
listLearner() gives error after mlrMBO is loaded

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#230]
library(mlr)
    library(mlrMBO)
    > listLearners()
    Error in get(fun, mode = "function", envir = parent.frame()) : 
      object 'makeRLearner.regr.kmforrester' of mode 'function' was not found

Current github version of both ``mlr`` and ``mlrMBO``

**Comment by berndbischl** [comment]
@mllg @jakob-r 
Can you please try to fix this in Dortmund?

mbo add a new mlr learner (kmforrester), apparently we now look in the wrong envir to access the constructor in Michels rewrite of listLearners

**Comment by mllg** [comment]
Not related to `listLearners` refactoring, also broken on CRAN. Introduced in https://github.com/mlr-org/mlr/commit/00e493e4102a5ba60b388d4ddd127773ad5b9012 via `functionBody()`.

**Comment by berndbischl** [comment]
> Not related to listLearners refactoring, also broken on CRAN

can you please still habe a look at this, so this is gone?

**Comment by mllg** [comment]
https://github.com/mlr-org/mlr/pull/911

**Comment by mllg** [comment]
Resolved via https://github.com/mlr-org/mlr/pull/911.
