### ISSUE TITLE
Tests randomly failing

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#238]
So it seems that tests may fail at random. 

In the last PR one commit passed, then I changed **one word** in the documentation and one test failed (in init_design), but worked after restarting.

**Comment by jakob-r** [comment]
yeah. its indeed bothering. it seem to be that some of the stochastic experiments don't reach some desired values. But I don't want to `set.seed` this. What is also strange is that I could nearly never reproduce these fails locally.
Can you give some details, link to travis logs etc.?

**Comment by ja-thomas** [comment]
Unfortunately I restarted the build so I think the log is gone (?).

But I think here: https://s3.amazonaws.com/archive.travis-ci.org/jobs/137526611/log.txt the same thing happened. (Seems to be the same test as I mentioned earlier).

I just rerun the test locally some times and it always passed. So maybe it has something to do with travis?

**Comment by berndbischl** [comment]
1) like i said, the issue already existed
https://github.com/mlr-org/mlrMBO/issues/90

2) now read run-all under tests please to understand what happens. and tests/helpers_zzz.R

3) the consensus that time was:
a) we dont want a seed on travis, as our tests and code should NEVER fail, whatever seed we use. we wanna SEE stochastic problems on travis, not artificially "avoid" them them by setting a seed
b) we want a seed for cran, getting stochastic errors THERE sucks.

4) we now have 2 parts on code where seeding is done. run-all and helpers_zzz.R.
please unify this now. also you should see that because of helpers.zzz you now locally always have a seed, but never one on travis. you might want to change this.

**Comment by ja-thomas** [comment]
Ah damn, I didn't found it because I only searched for open issues....

If I understand you correctly, we always set a seed as long as we aren't on travis but with `run-all.R` we can overwrite it and get a different seed to test with rng for local testing?


How do we want to handle it? I would say if we test on travis with rng we should also test locally with rng? Why do we want to see stochastic problems on travis but not locally?


And do we now have an "increased probability" of failing because of the proposed change in the default design #237 ? I cannot completely follow the discussion in #90 and what changes in `generateDesign` happened there

**Comment by berndbischl** [comment]
what you are doing in #237 should hopefully be completely unrelated, otherwise we should adapt out tests.

and for the seeding: do the seeding in one place, doc it with some comments and only set a seed when we are on cran.

**Comment by berndbischl** [comment]
to be honest, i have now idea how devtools does this, but envir var NOT_CRAN should tell you whether you are on cran or not. 
if you are, set the seed.

**Comment by ja-thomas** [comment]
I just changed the helpers_zzz in #244  so that we also use the same seed on travis that is run locally, with that all tests should run.

THIS SHOULD BE CHANGED BACK SOON. 

Just for the moment so that we are not failing anymore in master.

**Comment by jakobbossek** [comment]
> I just changed the helpers_zzz in #244 so that we also use the same seed on travis that is run
> locally, with that all tests should run.

On travis and locally you always use `set.seed(1)`.
On CRAN however, you use a random seed?
Should be the other way round.

**Comment by jakobbossek** [comment]
So the consens  is - as discussed in #90 - to use a fixed seed on CRAN and a random seed on travis, right?

**Comment by berndbischl** [comment]
1) NEVER use a random seed on CRAN. never. really. never.

2) i would even suggest seeding for travis now too

**Comment by jakobbossek** [comment]
@berndbischl Agree.

**Comment by jakobbossek** [comment]
@ping

**Comment by berndbischl** [comment]
@jakobbossek 
why are you pinging, I already responded?

**Comment by jakobbossek** [comment]
What is the status here?

**Comment by ja-thomas** [comment]
We have PR #240. But I'm not sure if this is still a problem or if it "solved itself".

I would suggest we wait and see if this still happens and then do something.

**Comment by jakob-r** [comment]
Really strange. It looks like the problem does not occur so often anymore. Maybe our surrogates are more well defined in the tests now.

I am okay with waiting and removing the bug label.
