### ISSUE TITLE
New getParamSet generic is breaking MBO

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#241]
I'm not sure if thats actually true or if I have some dependency problems.

Currently the `getParamSet` generic from https://github.com/berndbischl/ParamHelpers/issues/72 doesn't seem to work with MBO.

I have the current github versions of PH, smoof and MBO.

    > obj.fun = makeRastriginFunction(1)
    > mbo(obj.fun, control = makeMBOControl())
    Error: 'getParamSet' is not an exported object from 'namespace:smoof'

Ok so I think the problem is that in `getOptProblemParSet`, `smoof::getParamSet()` is called and after the update we use the generic.

**Comment by ja-thomas** [comment]
changing `smoof::getParamSet()` does fix it, but we still use this quite often in the tests.


Also, the package cannot be loaded via `load_all` anymore. Not sure why, but it could have something to do with the `export_all` "feature" in `load_all`.

    > load_all()
      Loading mlrMBO
      Error: 'getParamSet' is not an exported object from 'namespace:smoof'

    > load_all(export_all = FALSE)
       Loading mlrMBO
       Error: could not find function "checkInitDesign"

**Comment by jakobbossek** [comment]
I need to adapt smoof. The new generic in ParamHelpers is not yet considered.
Going to do it tomorrow. If not, remind me frequently here 😄

**Comment by ja-thomas** [comment]
Generally with the new generic we do not have to call `smoof::getParamSet()` anywhere anymore, we can always just use `getParamSet()` from PH, or am I missing something?

**Comment by ja-thomas** [comment]
Also, we then depend on the github version of smoof. Not that thats a problem, but we should add it in the current installation instructions.

**Comment by jakobbossek** [comment]
Ok. Obviously I also adapted smoof to the new generic. It now depends on PH >= 1.8. Are you sure that you have all current dev versions installed? Your example
```splus
obj.fun = makeRastriginFunction(1)
mbo(obj.fun, control = makeMBOControl())
```
works for me.

**Comment by ja-thomas** [comment]
Hm, strange. I just checked (actually deleted + reinstalled PH, smoof and mlrMBO) and I still get the same error.
