### ISSUE TITLE
MultiCrit test failing, bug in renderExampleRunPlot.MBOExampleRunMultiCrit

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#242]
The build is failing because of the multicrit: Parego tests.

This line in `addParegoWeightLines` seems to cause an error 

    weights = as.numeric(opt.path[idx$proposed[proposed.counter], c(".weight1", ".weight2")])

since `.weight1` and `.weight2` are no columns in the opt.path.

For the test it looks like this:

    > opt.path[idx$proposed[proposed.counter], ]
           x1        x2        y_1     y_2 dob eol error.message exec.time          ei error.model train.time prop.type propose.time
    11 0.03798726 0.9950951 0.03798726 9.34088   1  NA          <NA>         0 -0.01227088        <NA>      0.033 infill_ei        0.009

**Comment by berndbischl** [comment]
i am pretty sure this is due to the new meaning of columns that that with a "dot" in their name.

please rename the .weight columns generated by parego.
