### ISSUE TITLE
function extras do not work if initial design is preevaluated

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#249]
``` r
library(mlrMBO)
fn = makeSingleObjectiveFunction(
  name = "test", 
  fn = function(x) {
    res = sum(x^2)
    setAttribute(res, "extras", list(foo = runif(1)))
  }, 
  par.set = makeNumericParamSet(id = "x", len = 2, -2, 2))
ctrl = makeMBOControl()
ctrl = setMBOControlTermination(ctrl, iters = 3)
des = generateDesign(n = 10L, par.set = getParamSet(fn))
res1 = mbo(fn, design = des, control = ctrl)
#works fine
des$y = apply(des,1,fn)
res2 = mbo(fn, design = des, control = ctrl)
# [mbo] 1: x=-0.0312,-0.516 : y = 0.267 : 0.0 secs : infill_mean
# Error in addOptPathEl.OptPathDF(opt.path, x = x, y = y2, dob = dob, error.message = errmsg,  : 
#  Trying to add unknown extra(s): foo!
```

**Comment by jakobbossek** [comment]
Well, this usecase we obviously did not had in mind when we introduced extras.
Of course the problem is, that if we have a predefined design we have no access to the extras attributes. We could set these extras to NA in the opt.path for the initial design. However, to do so we need to know about them. Any ideas how to solve this?

**Comment by jakob-r** [comment]
I think we will have a mechanism in ParamHelpers soon that will solve this problem. We won't be further obliged to specify the extras beforehand as we will be able to add unknown extras "on the fly".

**Comment by berndbischl** [comment]
can we get a usecase before we solve a "hypothetical" problem?

**Comment by jakob-r** [comment]
The use case is quite clear outlined in the example:
I have an black box function i want to optimize with different MBO-Settings for benchmarking reasons. To not always having the initial design to be evaluated I want to pass it directly.
But additionally to the function value I want to optimize the black box function also generates output I want to log in the opt path.

**Comment by berndbischl** [comment]
> The use case is quite clear outlined in the example:

no its not, thats why i am asking...  usually text helps (so you get better answers....)

i can see the problem now, we basically need to add that info "somehow" to the initial design.

but this seems really low prio for version 1.0 as this is an extra extra extra feature?

**Comment by jakobbossek** [comment]
Proposal: Each column with column name prefix `extra.`, e.g., `extra.foo` will be treated as extras in the `opt.path`.

**Comment by jakob-r** [comment]
I like the idea. Then we should also add an option for `as.data.frame(opt.path, extra.names = TRUE)`.

**Comment by jakobbossek** [comment]
@berndbischl @danielhorn @janek what is your opinion?

**Comment by jakob-r** [comment]
This can be for a later milestome IMHO.

**Comment by berndbischl** [comment]
> This can be for a later milestome IMHO.

+1.
get the package on CRAN and finish the paper. this is an annoying bug, but we have to finish other stuff first.

**Comment by jakob-r** [comment]
This has been resolved with the dotted extras.
```r
library(mlrMBO)
fn = makeSingleObjectiveFunction(
  name = "test", 
  fn = function(x) {
    res = sum(x^2)
    setAttribute(res, "extras", list(.foo = runif(1)))
  }, 
  par.set = makeNumericParamSet(id = "x", len = 2, -2, 2))
ctrl = makeMBOControl()
ctrl = setMBOControlTermination(ctrl, iters = 3)
des = generateDesign(n = 10L, par.set = getParamSet(fn))
res1 = mbo(fn, design = des, control = ctrl)
#works fine
des$y = apply(des,1,fn)
res2 = mbo(fn, design = des, control = ctrl)
as.data.frame(res2$opt.path)
getOptPathEl(res2$opt.path, 12)
```
