### ISSUE TITLE
split up test-files

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#252]
Sometimes we run into the problem that tests are taking too long on travis:

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

I would like to split up the tests. Any wishes? My proposed categories:
- base
- multicrit
- multipoint

Any objections?

**Comment by berndbischl** [comment]
yes, my objection is:

why do we have a test that takes so long? splitting up test files makes maintenance harder. we should only do this if really needed.

**Comment by jakobbossek** [comment]
How does only splitting up the tests solve the running time issue?
We need to reduce the running time of some test cases.

**Comment by jakob-r** [comment]
Most tests are quite okay but in my branch i have some test scripts for the asynchronous mbo and they have to run a bit longer to establish asynchronity. This is like 10 seconds for each configuration. Maybe I can optimize it a bit but it will always take some time. 

Unfortunately it's tedious to run this test as an extra in my branch without having the split structure in general. That's why I wanted to establish that in the master.

Alternatively: Is there some possibility to generate output during `run_all` so that travis knows it's alive.

**Comment by berndbischl** [comment]
so you have (at least) one call in your new branch test which runs longer than 10 mins?
but the current mbo tests in master are ok? is that the status?

**Comment by jakob-r** [comment]
I dont know exactly what you mean, but yes master test is okay. The one call that takes over 10 mins is  `run-all.R`.

**Comment by berndbischl** [comment]
i mean: the current mbo master seems ok right? and you just have problems in your branch?
if you really cannot solve this in a better way in your branch, i am ok with splitting the tests up in groups in the master. 
but then i would suggest not to have too many of those. split up only if needed.

ok? does that help you?

**Comment by jakobbossek** [comment]
This is of minor importance now IMHO.
