### ISSUE TITLE
final.point.method and final.evals have no effect if n.objectives > 1L

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#253]
I will fix this in my noisy.mbmo branch today (since I need it for another project).

For the moment in the main branch it could be enough to throw an error in checkStuff?

**Comment by berndbischl** [comment]
either fix it, or throw that error in checkstuff and close very soon please

**Comment by danielhorn** [comment]
I think I fixed it via cb0a4827e5e08735c4b6e1f38733e2e5e6b1f197. I had to rewrite nearly the entire makeMBOResult structure. I'm not 100% happy with all parts of my code, at least some helper functions should be moved to ParamHelpers (see https://github.com/berndbischl/ParamHelpers/issues/140).

I coded this in my mbmo_noisy branch, since I need it for the experiments for our paper. I am not sure if we want to merge the complete branch.

**Comment by jakobbossek** [comment]
> I coded this in my mbmo_noisy branch, since I need it for the experiments for our paper. I am not > sure if we want to merge the complete branch.

We do not want to do this. However, there are just some simple lines of modified code. Can you do this ASAP?

**Comment by berndbischl** [comment]
@danielhorn 
i think we should not merge all noisy MBO multicrit metods, especially when we are unsure whether they are worthwhile. 

please do what @jakobbossek said ASAP. and just fix this issue here, which is only about final.evals

**Comment by jakob-r** [comment]
I am not so much in the topic but I am happy to have a look at the restructuring of the MBOResult. This was something that bothered me also when I restructured MBO but I didn't put so much effort in.

**Comment by danielhorn** [comment]
I will fix it after my vacation.

@jakob-r: feel free to look into the branch and comment on it. But I think we need some Kind of noise Handling in the opt.path bevore we can merge anything here

**Comment by jakobbossek** [comment]
@danielhorn: what is the status here?

**Comment by danielhorn** [comment]
As discussed, I added the check to checkstuff.

I don't think it is useful to add the real code yet, since we do not allow noisy multi.crit optimization at the moment. At some point in the future I will add the noisy multi.crit stuff, and than we can remove this check. But, later.
