### ISSUE TITLE
in the default learner, for the noisy case, always set jitter=TRUE as the default for regr.km

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#255]
1) ask @danielhorn why

2) please ALL read the mlr note of regr.km

**Comment by jakobbossek** [comment]
@danielhorn Why? 😄

**Comment by jakob-r** [comment]
Because dicekriging has the nice *"feature"* to predict the exact learned y even if you turned on the nugget effect which means that you have a noisy training set.

**Comment by berndbischl** [comment]
@jakobbossek 
please read the note in regr.km. read it **now**

**Comment by berndbischl** [comment]
PR is here #256

**Comment by jakob-r** [comment]
This is taken care of in PR #223
