### ISSUE TITLE
check that mboContinue works with multicore / parallelization

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#260]
In a recent experiment, it seemed like parallization did not work even though I used paralelStartMulticore before I ran mboContinue.
Short investigation here necessary.

**Comment by jakobbossek** [comment]
minimal non-working example neccesary.

**Comment by jakob-r** [comment]
It was my mistake. The target function was a bit more complex and I accidentally used variables from the global namespace that were non existent anymore in the new session - naturally.
