### ISSUE TITLE
Tutorial for multipoint & parallelization

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#267]
We currently do not have a tutorial page for multipoint as well as parallelization.

We should create one in the near future. Maybe we can combine them to one since they are pretty related. 

Should we wait until the asynchronous approach is in master?

**Comment by jakob-r** [comment]
(Parallelization throuh Multipoint Tutorial for MBO)[https://mlr-org.github.io/mlrMBO/articles/supplementary/parallelization.html]
