### ISSUE TITLE
Why do we have to set n.objectives

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#268]
Maybe I'm missing something, but isn't it completely pointless that we need to specify the number of objectives?

We always supply a smoof function where the number of objectives is already defined. Is there any situation where we have to set n.objective by hand? Otherwise I think we can (and should) remove it and just set it internally.

**Comment by danielhorn** [comment]
We talked about this a few weeks ago: We need to know the number of objectives in the setControl... functions, but the control object does not know the smoof function.

**Comment by ja-thomas** [comment]
Ah ok I see, not that great but makes sense
