### ISSUE TITLE
Tutorial is too slow. Each page should need less then 5 min

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#269]
because on the slow travis machines they have to finish in 10 mins but `in_depth_introduction.Rmd` seemst to be painfully slow. Probably focussearch and cmaes are configured suboptimally.

**Comment by ja-thomas** [comment]
Changed the example function to a lower dimension and stopped showing the output (so I don't have to fit it anymore). Should be much quicket now.

If the travis autobuild works we can close here.

**Comment by jakob-r** [comment]
I have to admit that I already changed CMAES to Focussearch in one point to make if faster. 

We can shortly discuss if we need CMAES in the Tutorial. If so we should configure it to run faster. And as it is mentioned in the text we should probably use it.

**Comment by ja-thomas** [comment]
Ah ok, I didn't notice that. 

I don't really care if we show CMAES as well.

**Comment by jakob-r** [comment]
Travis does not build the tutorials anymore and they also are fast enough.
