### ISSUE TITLE
Split Tutorial: Mixed Space Optimization should be own page.

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#280]
I already started it a bit but the text needs to be adapted

**Comment by ja-thomas** [comment]
We should decide for a good structure.

e.g.

- Quickstart
- Basics
   - Objective function
   - Initial Design
   - Surrogate Model
   - MBOControl
- Examples (?)
   - Continuous space
   - Mixed space
   - Machine learning
-  Advanced
   - Parallelization
   - Multi-Point
   - Multi-Criteria

**Comment by jakob-r** [comment]
It's its own page now
https://mlr-org.github.io/mlrMBO/articles/supplementary/mixed_space_optimization.html
