### ISSUE TITLE
MultiCrit should be MultiObjective

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#281]
For me there was always some confusion about the terms.

@ja-thomas already renamed multipoint.multicrit to moiboi in #279 

I want to propose to go one step further and rename everything MultiCrit to MultiObjective because in literature it is called Multi Objective Optimization and in smoof we have `makeMultiObjectiveFunction` so it becomes easily confusing when we additionally use the term of criteria in MBO for the infill criteria.

Please give your okay and I will rename it and open a PR for review.

**Comment by berndbischl** [comment]
> I want to propose to go one step further and rename everything MultiCrit to MultiObjectiv

thats not true and i dont see an advantage here, while the renaming will break lots of code.
both names are possible and we dont have to align names across multiple packages of different "teams"

 i would suggest to close

**Comment by berndbischl** [comment]
PS: I meant its not true that all guys call it multiobjective, and nobody uses multicrit.
(sorry, quoted not enough)

**Comment by jakob-r** [comment]
Advantages to call it Multi Objective
* uniformity with smoof
* Wikipedia calls it [Multi-Objective Optimization](https://en.wikipedia.org/wiki/Multi-objective_optimization)
* better separation from infill criteria in our package
* [![image](https://cloud.githubusercontent.com/assets/1888623/20596602/a3de5f6c-b23f-11e6-83a4-ffeaaa01eac5.png)](https://www.google.de/trends/explore?q=%22multi%20objective%20optimization%22,%22multicriteria%20optimization%22)
* It's called 
_ParEGO: an algorithm for multiobjective optimization of expensive functions_
Drawbacks
* We will have to rename it - that will take max 4 hours
* ?

**Comment by ja-thomas** [comment]
+1 for having it consistent

I don't really care if we call it multi criteria or multi objective, but if we change it, we should do it now (e.g. before the package is on CRAN).

**Comment by berndbischl** [comment]
i have no problem, it its about making it consistent and i really like effort to find good names
also *now* is a better time to change names than later when we are on CRAN.

still, just saying in principle, this is a veeeeeeery well known book on the subject: 
http://www.math.hcmus.edu.vn/~nvthuy/om/Multicriteria%20Optimization.pdf

@jakobbossek @danielhorn 
please vote

**Comment by danielhorn** [comment]
I am on Bernds side. Both names are used. Here are some examples
- There is a book by Matthias Ehrgott called "Multicriteria optimization" (Buh, Bernd, you stole my argument)
- There is a field called MCDM - Multi Criteria Decision Making

And my perfect reason for using multi.crit as name in the code: It is shorter :) We could use multi.obj, but I think it is way easier to "say" crit than obj.

**Comment by jakobbossek** [comment]
+1  for consistency.
In smoof I stick to multi-objective and this is also my preferred choice. Since we rely on smoof something like this is really inconsistent:
```splus
fn = makeMultiObjectiveFunction(...)
ctrl = makeMBOControl(...)
ctrl = someMBOControlSetter(multi.crit)
```
Thus +1 for `multi.obj`

**Comment by berndbischl** [comment]
argument for jakob: i just grepped the "R" folder for the term "objective" and use it a lot.
ok, and if it "smoothes" naming with smoof, too, :) then maybe its good.

let @jakobbossek also vote

**Comment by berndbischl** [comment]
ok, seems like we want it.
do it fast and consistent then close

**Comment by berndbischl** [comment]
democracy at work :)

**Comment by ja-thomas** [comment]
merged :)
