### ISSUE TITLE
Make infill criteria modular

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#284]
#Working on this in branch *infill_criteria_refactoring*.

Overview of what is left to do (incomplete):
- [x]  think of basic concept
- [x] implement makeMBOInfillCriterion body
- [x] adapt implemented infill criteria
   - [x] EI
   - [x] cb
   - [x] sd
   - [x] mean
   - [x] AEI
   - [x] EQI
   - [x] multifid
- [ ] think about how to maybe make multi-point methods modular as well
- [x] add docs for makeMBOInfillCriterion and export
- [x] rewrite setMBOControlInfill
- [x] rewrite docs of setMBOControlInfill
- [x] adapt all tests and examples 🐒 😴  
- [ ] adapt tutorial
- [ ] add `properties`? Let user filter for certain properties, e.g., infill criteria which are adequate for noisy optimization?
- [x] add `params` property and function `getMBOInfillParams(infill.crit.fun)` to get a list of parameters

Ideas and discussions requested 😃

**Comment by jakob-r** [comment]
[ ] implement way to store infill components in opt path 

Probably `makeMBOInfillCriterion` should have an argument `infill.components` that would be `c("se", "mean")` for the expected improvement. Or what do you think is best?

**Comment by jakobbossek** [comment]
See PR #286. Work in progress, but it works quite well already for single-objective stuff.
Please have a look at the current status and comment, make suggestions for improvements, naming and more.

**Comment by jakobbossek** [comment]
@berndbischl Please have a look at the PR as well and tell me your opinion.

**Comment by jakobbossek** [comment]
Closing for now. PR #286 is merged now 🎉
