### ISSUE TITLE
Arg Check for infill.crit does not work perfectly

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#289]
```
ctrl = makeMBOControl()
ctrl = setMBOControlInfill(ctrl, crit = factor("ei"))
```

This should throw an error imo.

Just happened with batchtools. It's pretty annoying since this takes some time to debug and the error was not informative in my case.

**Comment by jakobbossek** [comment]
IMO factors should be simply converted to character.

**Comment by jakobbossek** [comment]
See PR #290

**Comment by mllg** [comment]
NB: I've improved the error messages in checkmate to point you to the type mismatch.
