### ISSUE TITLE
simply running load_all show "run test" message

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#291]
this error is created because the helper scripts are parsed by devtools on "load_all"

**Comment by jakobbossek** [comment]
Is this a problem? This happens only locally and on TRAVIS.

**Comment by jakob-r** [comment]
I don't even understand what @berndbischl is talking about. Can I close?

**Comment by berndbischl** [comment]
run load_all locally

```
Work dir: /home/bischl/cos/mlrMBO
> load_all()
Loading mlrMBO
Loading required package: mlr
Loading required package: ParamHelpers
Loading required package: smoof
Loading required package: checkmate
Run test with seed: 5
```

the last line is stupid.
the problem is that devtools sadly now executes the "helper" unit test files.
and the print is just one problem, the configureMlr statements are also executed. 

does somebody know how to avoid this? 
yes, this is not urgent but i dont like this
@mllg

**Comment by jakob-r** [comment]
It looks like hadley is going to out the functionality of `load_all()` into a package called `pkgload`. We should wait until this is done before taking action.

**Comment by berndbischl** [comment]
> It looks like hadley is going to extract the functionality of load_all() into a package called pkgload. We should wait until this is done before taking action.

thank you for the info.

lets be all aware than of what I wrote in the thread here, and I will close now
