### ISSUE TITLE
unit tests should NOT create warnings

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#292]
i see this. this must be looked at and fixed

Warnings -----------------------------------------------------------------------

1. mbo works with different learners (@test_different_learners.R#77) - filter.proposed.points is not set in the control object. This might lead to the 'leading minor of order ...' error during model fit.

2. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#46) - filter.proposed.points is not set in the control object. This might lead to the 'leading minor of order ...' error during
 model fit.

3. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#68) - The response has five or fewer unique values.  Are you sure you want to do regression?

.............

47. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: fill

48. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: z

49. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: fill

50. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: z

51. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: fill

52. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: z

53. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: fill

54. renderExampleRunPlot produces list of ggplot2 objects (@test_exampleRun.R#92) - Ignoring unknown aesthetics: z

55. plot single-objective (@test_plot_MBOResult.R#16) - replacing previous import by ‘utils::capture.output’ when loading ‘GGally’

56. plot single-objective (@test_plot_MBOResult.R#16) - replacing previous import by ‘utils::head’ when loading ‘GGally’

57. plot single-objective (@test_plot_MBOResult.R#16) - replacing previous import by ‘utils::installed.packages’ when loading ‘GGally’

58. plot single-objective (@test_plot_MBOResult.R#16) - replacing previous import by ‘utils::str’ when loading ‘GGally’

59. plot multi-objective (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_point).

60. plot multi-objective (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_path).

61. plot multi-objective (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_point).

62. plot multi-objective (@test_plot_MBOResult.R#30) - Removed 2 rows containing missing values (geom_path).

**Comment by mllg** [comment]
I'm not that familiar with ggplot, I guess its much faster if the original authors of the plotting functions would have a quick glimpse.

**Comment by jakobbossek** [comment]
PR #301 fixes ggplot warnings.

**Comment by jakobbossek** [comment]
There are no more warnings. Closing.
