### ISSUE TITLE
plotEAF masks PH::plotEAF

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#294]
either unexport this, or completely move it to PH
is there anything specific in there?

**Comment by danielhorn** [comment]
It's copy-paste in PH and MBO, and the PH version is the "better" one.

IMHO just remove it from MBO

**Comment by berndbischl** [comment]
ok do it

**Comment by danielhorn** [comment]
See #299

**Comment by danielhorn** [comment]
Second try #300
