### ISSUE TITLE
examples should not run more > 5 secs

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#295]
ecking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ... OK
Examples with CPU or elapsed time > 5s
     user system elapsed
mbo 5.396  0.032   5.488
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘run-examples.R’^C [87s/88s]
 ERROR
Running the tests in ‘tests/run-examples.R’ failed.
Last 13 line

**Comment by mllg** [comment]
I need to find a slow computer to reproduce this ;)

**Comment by berndbischl** [comment]
just make the example faster in general

**Comment by berndbischl** [comment]
simply reduce iters?

**Comment by berndbischl** [comment]
and reduce infill focus settings, that will do it
