### ISSUE TITLE
Error in: proposing random points because of failed model

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#302]
MBO tries to store mean and se prediction of the model in the opt.path. If the model failed, there is neither mean nor se prediction, but MBO still tries to store them -> error

```
library(mlrMBO)
library(smoof)
configureMlr(show.learner.output = FALSE, on.learner.error = "quiet")

obj.fun = makeSingleObjectiveFunction(
  name = "Sine",
  fn = function(x) sin(x),
  par.set = makeNumericParamSet(lower = 3, upper = 13, len = 1),
  global.opt.value = -1
)

ctrl = makeMBOControl(propose.points = 1)
ctrl = setMBOControlTermination(ctrl, iters = 1L)
ctrl = setMBOControlInfill(ctrl, crit = crit.ei, opt = "focussearch", opt.focussearch.points = 500L)

lrn = makeLearner("regr.km", predict.type = "se", covtype = "matern3_2")

design = generateDesign(6L, getParamSet(obj.fun), fun = lhs::maximinLHS)
# Make sure the model will break in iter 1
design = rbind(design, design[5, ] + 1e-15)

run = mbo(obj.fun, design = design, learner = lrn, control = ctrl)

Computing y column(s) for design. Not provided.
[mbo] 0: x=6.28 : y = -0.0051 : 0.0 secs : initdesign
[mbo] 0: x=6.68 : y = 0.386 : 0.0 secs : initdesign
[mbo] 0: x=10.2 : y = -0.683 : 0.0 secs : initdesign
[mbo] 0: x=12.7 : y = 0.101 : 0.0 secs : initdesign
[mbo] 0: x=4.48 : y = -0.974 : 0.0 secs : initdesign
[mbo] 0: x=8.66 : y = 0.69 : 0.0 secs : initdesign
[mbo] 0: x=4.48 : y = -0.974 : 0.0 secs : initdesign
[mbo] 1: x=9.58 : y = -0.152 : 0.0 secs : infill_ei
Error in addOptPathEl.OptPathDF(opt.path, x = x, y = y2, dob = dob, error.message = errmsg,  : 
  Trying to add extras but missing: se,mean!
```

PS: "infill_ei" in iteration 1 is also wrong, it should be "random because of error model"

**Comment by berndbischl** [comment]
thx. can you add a PR with test + fix?

**Comment by danielhorn** [comment]
No. I looked at this for quiet some time and I did not find a good fix. We need a special information (the ingredients of an infill criteria), but it is not available where it is needed. I suggest to wait for @jakobbossek to finish the refactoring of the infill.crits #284.

I could make a PR with my hotfix, if you want.

**Comment by berndbischl** [comment]
> I could make a PR with my hotfix, if you want.

does this solve the problem, at least with "ugly" code?
then yes, lets look at it.

**Comment by danielhorn** [comment]
I looks liek @jakobbossek is finishing the refactoring in a few days? Then I think we should wait.

My ugly code only works for EGO using EI, I would have to write more ugly code for each infill criterion.

**Comment by berndbischl** [comment]
> I looks liek @jakobbossek is finishing the refactoring in a few days? Then I think we should wait.

we will merge this in the next days, it looks extremely good already

**Comment by berndbischl** [comment]
@danielhorn 
also review jakobs PR pls so we be even faster
