### ISSUE TITLE
Make control$multiobj.dib.sms.eps param of dib infill criterion

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#308]

**Comment by jakobbossek** [comment]
Then `multiobj.dib.indicator` is also a parameter of the infill criterion, right?

**Comment by danielhorn** [comment]
Short answer: Yes

Long answer: It's a really special one. At the moment we have 4 multi-obj algorithms. ParEGO, MSPOT, SMS-EGO and epsilon-EGO. Via the multicrit.method one can choose between ParEGO, MSPOT and DIB. DIB ist the "meta-idea" of a class of algorithms. Via the parameter multiobj.dib.indicator one can switch between the two DIB type algorithms SMS-EGO and epsilon-EGO.

**Comment by jakobbossek** [comment]
@danielhorn Thanks for the rapid answer.
To be honest this is not easy to understand for someone who is not that familiar with multi-point/-objective MBO. Moreover, we need to refactor that multipoint/-objective stuff as well, since everything is kind of hardcoded and not extensible.

To finish this one here: going to add `sms.eps` as another parameter of the DIB infill criterion an close here.

**Comment by jakobbossek** [comment]
Done
