### ISSUE TITLE
Remove cb.inflate.se param from CB/DIB

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#309]

**Comment by berndbischl** [comment]
no, remove it completely for now

**Comment by berndbischl** [comment]
daniel said:

I am not sure if the cb.inflate.se parameter is useful for dib. The lambda value has a rather different effect here than in the CB. My suggestion: Rename to dib.lambda, delete cb.inflate.se, add dib.q from Tobias formula.

bernd said: 
have we EVER used the inflate param? or benchmarked it? my guess is "no".
dont bloat with unused features. remove it, possibly note it down as an idea to try for a future project, but not in the tracker.

**Comment by jakobbossek** [comment]
Remove it only for DIB or for CB as well?

**Comment by berndbischl** [comment]
totally delete that param for now.
or @mllg has to veto this *now*

**Comment by mllg** [comment]
Ok to remove.

**Comment by jakobbossek** [comment]
Done
