### ISSUE TITLE
We don't test the automatically generated learner

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#311]
In all tests we manually generate a learner as far as I can see.
I had the issue that in another package `rcheck` won't work with `mbo.learner = makeLearner("regr.km", predict.type = "se", covtype = "matern5_2", optim.method = "gen", nugget.estim = TRUE, jitter = TRUE)` because of `optim.method = "gen"`.
After deleting that it worked.

**Comment by ja-thomas** [comment]
We have to change the default mbo learners anyways based on our benchmark results. I'll add tests for them as soon as I do.

I had to wait for the refactoring of the infill crits, but as that is done, I'll do a PR soon

**Comment by berndbischl** [comment]
yup pls test that, seems simple, close soon :)

**Comment by ja-thomas** [comment]
see PR #312

**Comment by ja-thomas** [comment]
fixed
