### ISSUE TITLE
Fix vignettes

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlrMBO#316]
They are in a funny state. We should agree on a minimal vignette for now, but do this one right.

**Comment by berndbischl** [comment]
@mllg @jakob-r @ja-thomas 
can someone take the lead here? make it minimal, copy the rest somewhere else. 

it should not look like "bullshit". 

i can certainly help with reviewing and doing some changes

**Comment by jakob-r** [comment]
I am on it. 
This one should be fine: http://mlr-org.github.io/mlrMBO/articles/mlrMBO.html
Prroblem with the other is that they have cross references or at least teasers and should to be published all together somehow.

**Comment by jakob-r** [comment]
I think the state now is okay. For more specific things we have separate issues.
