### ISSUE TITLE
Stochastic errors again

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#324]
This seems to happens from time to time. 

```
  > test_check("mlrMBO")
  1. Failure: multipoint cb (@test_multipoint_cb.R#16) ---------------------------
  res$y is not strictly less than 0.1. Difference: 0.056
```

**Comment by ja-thomas** [comment]
So we test `expect_lt(res$y, 0.1)`

This seems like a bad test, as it can break just by chance and we do not want to test the "performance" of mlrMBO in our tests.

This is done in multiple tests:

```
tests/testthat/test_multipoint_moimbo.R
27:        # expect_lt(gap, 0.1)

tests/testthat/test_optimizers.R
13:    expect_lt(or$y, 1)

tests/testthat/test_infillcrits.R
82:  expect_lt(or$y, 50)

tests/testthat/test_infill_opt_ea.R
13:  expect_lt(res$y, 1e-1)
26:  expect_lt(res$y, 1e-1)

tests/testthat/test_multipoint_cb.R
16:  expect_lt(res$y, 0.1)

tests/testthat/test_termination_criteria.R
36:  expect_lt(or$y, target.fun.value)

tests/testthat/test_multipoint_cl.R
10:  expect_lt(res$y, 0.1)

```

**Comment by ja-thomas** [comment]
I just relaxed the boundary of the test (from 0.1 to 0.15) in #323, so that this specific test hopefully won't fail  just by chance anymore.

But should we maybe remove these kind of tests completely? @berndbischl @mllg @jakob-r @jakobbossek

**Comment by jakob-r** [comment]
We don't want to remove them completely because we want to make sure the optimization is running in the right direction. If one accidentally changes a sign, the tests should notice that. :wink:

**Comment by danielhorn** [comment]
Perhaps we simply want to check that the final result is better than the best point of the initial design?

**Comment by jakob-r** [comment]
That won't work because the default is to choose the best point of the opt.path as the result. That includes the initial design.

**Comment by danielhorn** [comment]
I meant strictly better. "<" and not "<="

**Comment by jakob-r** [comment]
My bad.

**Comment by berndbischl** [comment]
why dont we simply fix the seed for the tests for now?

**Comment by berndbischl** [comment]
i also am against removing such tests completely
 

> We don't want to remove them completely because we want to make sure the optimization is running in the right direction. If one accidentally changes a sign, the tests should notice that.

**Comment by ja-thomas** [comment]
since #323 was merged, the problematic test is relaxed. I'll close here
