### ISSUE TITLE
Infill settings without meaning

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#331]
All the settings for specific infills don't have any meaning because we did our refactoring just halfheartedly.

The actually used function for the infill is obtained by `getInfillCritFunction()` which just creates the InfillCritFunction with all default values.

Do we have a test that tries to use a own infill-crit in `setMBOControlInfill(crit = ...)`. Because that should fail!
Also we obviously did not have a test that checks wheter the InfillCrit settings have an effect at all.

Sad!

**Comment by berndbischl** [comment]
can you really post an examples where something breaks or post a code snippet where code looks dubious?
otherwise it is hard to understand what you mean...

**Comment by jakobbossek** [comment]
Oh shit! Had a short look at this. I think @jakob-r is right.
Thanks for figuring this out. IMHO we do not need the following line in `proposePointsByInfillOptimizaton`. This line simply overwrites the selected infill critetion 😢 
```
infill.crit.fun = getInfillCritFunction(infill.crit.id)$fun
```
since `infill.crit$fun` is the function we want to use.

**Comment by jakob-r** [comment]
Exactly. That's the line. I am on it and I will add some tests at least for the CB where it is kind of obvious

**Comment by berndbischl** [comment]
what i see is:
getInfillCritFunction(string) should be completely removed? as the crit is now always an object?

**Comment by jakobbossek** [comment]
Actually we should drop `getInfillCritFunction`. It is no longer needed.

**Comment by berndbischl** [comment]
i was faster, you suck

**Comment by jakob-r** [comment]
I am not totally sure. What about `infillOptNSGA2.R`.

Anyhow. I am on it and I might delete it if its not called anymore.

**Comment by berndbischl** [comment]
> I am not totally sure. What about infillOptNSGA2.R.

i think this is still OK, but please *ask* (with more than 3 words....) if you only feel *slightly* unsure here, or anywhere else. 

it is really hard to check whether the algorithm still "work as intended" through unit tests and we dont want o break everything

**Comment by jakob-r** [comment]
please continue conversation here: https://github.com/mlr-org/mlrMBO/pull/334
