### ISSUE TITLE
infill crit object in zzz are not documented and cb1 is wrong

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#332]
- [x] we need a doc page to explain what the objects are

- [x] cb1 is NOT cb with lambda =1, but CB with lambda = "auto", see infillcrits.r for docs

--> 
- [x] create cb1 with lambda = 1 and cb with lamda = NULL (auto)

- [ ] if you print the cb with lam = 0, the printout looks strange and should be improved, at least print the NULL

**Comment by berndbischl** [comment]
if one is at it: please add a line in the printer whether the crit is minized

**Comment by berndbischl** [comment]
> we need a doc page to explain what the objects are

done, in other PR

**Comment by berndbischl** [comment]
taking this over now

**Comment by berndbischl** [comment]
> cb1 is NOT cb with lambda =1, but CB with lambda = "auto", see infillcrits.r for docs

make docs better

**Comment by berndbischl** [comment]
> create cb1 with lambda = 1 and cb with lamda = NULL (auto)

done

**Comment by berndbischl** [comment]
> if you print the cb with lam = 0, the printout looks strange and should be improved, at least print the NULL

works for now, added a test

**Comment by berndbischl** [comment]
> if one is at it: please add a line in the printer whether the crit is minized

done

**Comment by berndbischl** [comment]
PR is #339

**Comment by jakob-r** [comment]
If I see this right. everything here is solved.

**Comment by berndbischl** [comment]
yes, done
