### ISSUE TITLE
makeMBOInfillCriterionCB lambda default 

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlrMBO#333]
@berndbischl and I agreed, that at the moment the style of `makeMBOInfillCriterionCB` is not very good. This function is called quite often and each time the lambda value is again determined. 
Intstead it should be fixed once the par.set ist known and then probably also accessible through `$params$cb.lambda`.

**Comment by berndbischl** [comment]
this code is the context

```
  makeMBOInfillCriterion(
    fun = function(points, models, control, par.set, design, iter, attributes = FALSE) {
      if (is.null(cb.lambda))
        cb.lambda = ifelse(isNumeric(par.set, include.int = TRUE), 1, 2)
```

lambda should be set someplace else, very early in the beginning. as we cannot do this in the control object, do it in beginning of mbo.

please resolve this soon

**Comment by berndbischl** [comment]
do this in checkStuff, I guess. possibly rename checkstuff to checkAndInitStuff, or whatever

**Comment by ja-thomas** [comment]
I have a fixed this, but we have to merge #334 first

**Comment by berndbischl** [comment]
ok, go, was merged

**Comment by jakobbossek** [comment]
IMHO setting these settings in `checkstuff` is bad design. The infill criteria refactoring aimed to unbind the infill logic from the mbo internals. This way we kind of bind CB logic to another function.

**Comment by berndbischl** [comment]
> IMHO setting these settings in checkstuff is bad design. The infill criteria refactoring aimed to unbind the infill logic from the mbo internals. This way we kind of bind CB logic to another function.

not untrue, but you need to make a constructive suggestion. the current state is even worse. 
and you need to have the par.set to autoset lambda

**Comment by berndbischl** [comment]
if you want to have a clean OO design, you probably would add 

autosetConstants(learner, par.set, control) 

to the method of the infill crit class. the default is NULL / empty, but you can overwrite this so a crit sets its internal vars a bit later. 

you call this somewhere in the beginning of mbo, probably directly after checkStuff.

get what i mean? like it?

**Comment by jakobbossek** [comment]
You are faster again. This is my proposal as well. Filling checkstuff is really a bad solution.
We should work on extending the infill crit methods.

**Comment by berndbischl** [comment]
i hate you but are correct

**Comment by jakob-r** [comment]
ok - so who is doing it?

**Comment by ja-thomas** [comment]
I'm sure I 100% understand the `autosetConstants` idea.

Basically you still initialize `makeMBOInfillCriterionCB` with the `NULL` default and we do the same thing that we do in the PR in `checkStuff` but in a separate function, in which all problem dependent infill criterion defaults are collected?

Is that about right?

**Comment by berndbischl** [comment]
yes, but that function is an (empty) generic, which has methods for makeMBOInfillCriterion subclasses.

so the concrete code is associated with the class. and we have a clean OO design

got it?

**Comment by berndbischl** [comment]
and i would call it  

initializeCriterion
