### ISSUE TITLE
infill crit cb and minimze

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#338]
currently for CB this seems to be set to "TRUE"

but thats kinda wrong, because it depends on the objective function whether to want to min or max this. 

- either we set this to NA, and overwrite it when we know the objective function
- or we at least document what happens exactly and why min=TRUE is OK

@ja-thomas @jakob-r 
pls lets solve this soon

**Comment by jakob-r** [comment]
You can say the same about `makeMBOInfillCriterionMeanResponse`. Anyway. 
Technically all Infillfunctions will be minimized internally and are programmed that way (e.g. `-ei`).
The only place where we use that information is in `getMBOInfillCriterionDirection()` which again only is used in `renderExampleRunPlot1d()`.

**Comment by berndbischl** [comment]
> You can say the same about makeMBOInfillCriterionMeanRespons

correct, good point.

> Technically all Infillfunctions will be minimized internally and are programmed that way (e.g. -ei).
> The only place where we use that information is in getMBOInfillCriterionDirection() which again only is used in renderExampleRunPlot1d().

i am asking as we now have meta information in the objects, which is potentially wrong. that is never good.
shall we set it to NA, and then set in the autoset function we want to add to class anyway? see here #333

**Comment by danielhorn** [comment]
Perhaps we want to replace the direction with a factor with 4 levels:
Allways Minimize, Allways Maximize, Use control$minimize, Use !control$minimize

**Comment by jakob-r** [comment]
I am still struggeling to find a good name but I also would remove the `minimize` property and change it for something like `opt.direction %in% c("minimize", "maximize", "as.obj.function")`. I can't think of any case that would be `"opposite.to.obj.function"`.

**Comment by berndbischl** [comment]
> infill$opt.direction

name ok.


> % c("minimize", "maximize", "as.obj.function")

"minimize", "maximize", "objective", "-objective"

i would have all four, for completeness.

**Comment by jakob-r** [comment]
what about "minimize", "-minimize", "objective", "-objective"?
just kidding. I am courious to hear @danielhorn and @jakobbossek opinions.

**Comment by danielhorn** [comment]
"minimize", "maximize", "objective", "anti.objective"

although I can not think of an application for anti.objective yet, there may be one

**Comment by berndbischl** [comment]
> although I can not think of an application for anti.objective yet, there may be one

then lets stay with 

> "minimize", "maximize", "objective",

**Comment by berndbischl** [comment]
and move forward

we do not maybe need a not so intuitive name if we cannot think of a usecase

**Comment by jakobbossek** [comment]
JB does not get the point at the moment. Why are two states, i.e., minimize and maximize, not enough?

**Comment by berndbischl** [comment]
> JB does not get the point at the moment. Why are two states, i.e., minimize and maximize, not enough?

read my first post? 

you call the constructor for CB. the state is set. what you you choose?
(minimize is wrong, maximize is also wrong)

**Comment by jakobbossek** [comment]
Ah. Ok. Thanks, got it.

**Comment by jakob-r** [comment]
PR #343

**Comment by jakob-r** [comment]
Has been solved with PR #343
