### ISSUE TITLE
rename all "Criterion" to "Crit"

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#348]
We want shorter names

**Comment by jakobbossek** [comment]
@berndbischl I do understand your arguments, but ...
... I am confused about the naming (issues) in general in all our packages.
Are there any agreed rules when to shortcut a part of a function name?
E.g., here we propose to shorten `makeMBOInfillCriterion*` to `make{MBO}InfillCrit`.
In ParamHelpers for instance we have a function called `convertListOfRowsToDataFrame`.
We could shorten this one to `convListOfRowsToDataFrame` or `convertListOfRowsToDf`.
The latter should be fine, since there is `makeOptPathDF` instead of `makeOptPathDataFrame`.

**Comment by jakobbossek** [comment]
See discussion in #350

**Comment by berndbischl** [comment]
> Are there any agreed rules when to shortcut a part of a function name?

I really dont think you can put this into "mathematical rules". It's language.
There are actually studies about this, and giudelines in software engineering.
(Not going to google this now)
These guidelines basically say: Software is easier to maintain when names are precise and expressive, but not too long. 
And yes, these rules are still a bit fuzzy, and nobody can eliminate all exceptions and cornercases. 


> In ParamHelpers for instance we have a function called convertListOfRowsToDataFrame.
> We could shorten this one to convListOfRowsToDataFrame or convertListOfRowsToDf.
> The latter should be fine, since there is makeOptPathDF instead of makeOptPathDataFrame.

1) I am not saying names are always perfect, in every package I ever wrote.

2) What it the obvious difference between mbo and PH....? And...?
One is on CRAN the other is not. Breaking code (or deprecating stuff) just for these "aesthetic" reasons is not worth it.

3) Guess why I am trying to start the discussion now BEFORE we release....

**Comment by berndbischl** [comment]
it's actually to some extend on wikipedia

https://en.wikipedia.org/wiki/Naming_convention_(programming)#Length_of_identifiers

**Comment by jakobbossek** [comment]
> > Are there any agreed rules when to shortcut a part of a function name?
> I really dont think you can put this into "mathematical rules". It's language.

This is not the point, but we have kind of coding and naming conventions, right?

> There are actually studies about this, and giudelines in software engineering.
> (Not going to google this now)
> These guidelines basically say: Software is easier to maintain when names are precise and
> expressive, but not too long.
> And yes, these rules are still a bit fuzzy, and nobody can eliminate all exceptions and cornercases.

Yes. But I prefer lengthy, but consistently named names instead of mixup.

> In ParamHelpers for instance we have a function called convertListOfRowsToDataFrame.
> We could shorten this one to convListOfRowsToDataFrame or convertListOfRowsToDf.
> The latter should be fine, since there is makeOptPathDF instead of makeOptPathDataFrame.
> I am not saying names are always perfect, in every package I ever wrote.
>
> What is the obvious difference between mbo and PH....? And...?
> One is on CRAN the other is not. Breaking code (or deprecating stuff) just for these "aesthetic" 
> reasons is not worth it.
>
> Guess why I am trying to start the discussion now BEFORE we release....

Ok. All good points @berndbischl. This is why the discussion takes place. We could simply close and stick to one opinion. However, I am interested in the opinion of @jakob-r, @ja-thomas, @danielhorn, @mllg

**Comment by berndbischl** [comment]
> This is not the point, but we have kind of coding and naming conventions, right?

no, we dont have rules for this. because we cannot have them for something like this....

and: i really do not see, where i ever wanted "mixup" or something "inconsistent"?
please post an example?

and everybody can have opinions, sure. but in science also arguments count. and reading about stuff.
did you do that?

>> longer identifiers may be disfavored because of visual clutter
>>  in many situations a longer identifier simply clutters the visible code and provides no perceived benefit

**Comment by jakobbossek** [comment]
> it's actually to some extend on wikipedia
> https://en.wikipedia.org/wiki/Naming_convention_(programming)#Length_of_identifiers

Well, most of the points in this wiki article are kind of opposing/conflicting. Sure, on the one hand we want short identifiers/function names/object names. On the other side we aim for identifiers, that are easy to remember. Generally, we are confronted with a highly subjective and multi-objective problem. 

Moreover, I like my argument of consistency. Sure, we have a lot of packages now with hundreds of functions. However, all these packages kind of interact and thus consistency is even more valuable. 

I think this is an important issue and we should agree on kind of a long-range solution.

**Comment by berndbischl** [comment]
> Well, most of the points in this wiki article are kind of opposing/conflicting. Sure, on the one hand we want short identifiers/function names/object names. On the other side we aim for identifiers, that are easy to remember. Generally, we are confronted with a highly subjective and multi-objective problem.

yup. i know. its opinions and feelings and preferences to a larger extend. 

> Moreover, I like my argument of consistency.

well, i dont understand it. what is it exactly. i do agree that we need to sort this out.
can you please explain again what you want to have "consistent"

**Comment by jakobbossek** [comment]
With consistency I basically mean that I do not want to think about "is it mboFun" or just "fun". 
Some time ago - as war as I remember - you introduced that `MBO` prefix and this is really fine. 
Beside this, function names in our packages are still quite long in comparisson to the majority of R packages, but I do not see this as a drawback. It is kind of beneficial!

Another argument: since most people use editors with code completion, e.g., R studio, the argument of longer function names is kind of defused 😉

**Comment by berndbischl** [comment]
I can try to clarify my viewpoint with a few comments:

- i dont think we should put the package name into every object and function name. (not saying you want that, i guess. or hope?). that has no value and people do that when they dont understand namespaces IMHO.

- longer names are better than short one, if the extra info makes the name more informative and precise (especially: clears up potential mixups)

- longer names are worse than short one, if the extra-letters dont give you anything. my example is: InfillCrit vs. InfillCriterion. The latter has no benefit, but will visually clutter. Even worse it's hard to type! Or We could also use AcquisitionFunction. Thats is the worst of the 3 IMHO :)

- for certain situations fixed rules are needed for consistency. We had so far:
getClassMember. There should be no exceptions for these rules. I dont have a complete list at hand at the moment. but we can try to compile this.

**Comment by berndbischl** [comment]
> Beside this, function names in our packages are still quite long in comparisson to the majority of R packages, but I do not see this as a drawback. It is kind of beneficial!
> 
> Another argument: since most people use editors with code completion, e.g., R studio, the argument of longer function names is kind of defused

That really is not true, at least as clear cut as you try to put this. 
It's in the WP article, and there are studies about this. The longer the name, the more visual clutter. And you can read then code much less well. And being able to read code well is the most important thing. More important than writing (what you seem to refer to)

**Comment by berndbischl** [comment]
Example:

optimizeBlackBoxFunctionWithCovarianceMatrixAdapationAlgorithmAndRestartStrategie(now.comes.a.really.precise.argument.name, what.about.the.other.ten.args)

**Comment by jakobbossek** [comment]
Would your really write this one? I guess you would rather proceed in a modular fashion and define/export this one: `optimizeBlackBoxFunction(method = "cma", restarts = 992424L, ...)` 😉

**Comment by berndbischl** [comment]
general comment: 

we can close this, i dont hate "criterion" this much. 
but maybe we should try to write down more "rules" for this in the style guide?

**Comment by berndbischl** [comment]
> optimizeBlackBoxFunction(method = "cma", restarts = 992424L, ...)

function name is much too long (my serious opinion for this example).

you are inconsistent. "cma" is really imprecise and an abbreviation. please use  "covariance-matrix-adaptation" (irony, but seems to use your consistent rule set? why is a shortcut here ok?)

**Comment by jakobbossek** [comment]
> i dont think we should put the package name into every object and function name. (not saying you > want that, i guess. or hope?). that has no value and people do that when they dont understand 
> namespaces IMHO.

I do not see a problem in integrating MBO in each function.

> longer names are better than short one, if the extra info makes the name more informative and 
> precise (especially: clears up potential mixups)

Yeah! Right! I agree with this one. However, we do not stick to it in each 

> longer names are worse than short one, if the extra-letters dont give you anything. my example is:
>  InfillCrit vs. InfillCriterion. The latter has no benefit, but will visually clutter. Even worse it's hard to
> type! Or We could also use AcquisitionFunction. Thats is the worst of the 3 IMHO :)

Counterexample: `InfCrit`
This one is fully readable if one is familiar with infill criteria and model-based optimization.

> for certain situations fixed rules are needed for consistency. We had so far:
> getClassMember. There should be no exceptions for these rules. I dont have a complete list at 
> hand at the moment. but we can try to compile this.

Agree!

**Comment by jakobbossek** [comment]
> > optimizeBlackBoxFunction(method = "cma", restarts = 992424L, ...)
> function name is much too long (my serious opinion for this example).

> you are inconsistent. "cma" is really imprecise and an abbreviation. please use "covariance-
> matrix-adaptation" (irony, but seems to use your consistent rule set? why is a shortcut here ok?)

Ahhh! I need another beer now. Lets talk about this via phone. I am tired of writing 😉

**Comment by berndbischl** [comment]
> Lets talk about this via phone.

grrrr. now?

**Comment by berndbischl** [comment]
man, this is the worst thread. note to myself, never start such a discussion ever again :)

**Comment by jakobbossek** [comment]
Now is fine 😆

**Comment by berndbischl** [comment]
had a good discussion with @jakobbossek 
lets not rename it.

taking the request back

**Comment by jakob-r** [comment]
8/10 would let you discuss again

**Comment by berndbischl** [comment]
> 8/10 would let you discuss again

:(
