### ISSUE TITLE
mini renaming

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#350]
do we REALLY want "MBO" in every name?

just makes the names longer, without any more info

and namespaces exist for this

(sorry, about this issue)

**Comment by berndbischl** [comment]
@jakob-r @mllg @ja-thomas

**Comment by jakobbossek** [comment]
Just 3 more characters to write 🙄

**Comment by berndbischl** [comment]
i also want BB in every name please. to honor the original author

**Comment by berndbischl** [comment]
@mllg say something too
lets get this out of the way quickly

**Comment by ja-thomas** [comment]
I think it is useful when we can avoid naming conflicts e.g. `makeMBOControl` -> `makeControl` or `mboContinue` ->  `continue` is a bad idea...

(I know that these are not the function that you had in mind, but currently we are at least consistent)

**Comment by berndbischl** [comment]
> I think it is useful when we can avoid naming conflicts e.g. makeMBOControl -> makeControl or mboContinue -> continue is a bad idea...

ok, i did not want to suggest to remove it there.

**Comment by berndbischl** [comment]
what i mean is
InfillCrit, getInfillCritFoo

is IMHO better than
MBOInfillCrit, getMBOInfillCritFoo

**Comment by berndbischl** [comment]
the point is: MBOControl needs the "MBO"
the InfillCrit does not

**Comment by jakobbossek** [comment]
I do not get it. IMHO MBO/mbo should be either part of all MBO functions or completely removed.
This mixup, e.g., `getInfillCrit` and `mboContinue`, is highly inconsistent and hard to remember.

**Comment by berndbischl** [comment]
not sure i can explain it in writing, but do not get your point :)

why are you saying

> MBO/mbo should be either part of all MBO functions or completely removed.

i can pick other words too, that are part of some names and not others. 

mboContinue is NOT called that way because it lives in our package. it is called that way, because of the *function* "mbo". as it does a related thing. it continues the run. (plus command-completion-similarity)
and because "continue" itself is a really bad name, as it is very generic. 

The same holds true for MBOControl. Exactly the same 2 reasons. 

MBOInfillCrit does not help you at all. You just waste 3 letters.

I can close this, we dont need to argue 5 weeks about this. But names should always be good IMHO....

**Comment by jakobbossek** [comment]
Sorry, double posting (see #348)

@berndbischl I do understand your arguments, but ...
... I am confused about the naming (issues) in general in all our packages.
Are there any agreed rules when to shortcut a part of a function name?
E.g., here we propose to shorten `makeMBOInfillCriterion*` to `make{MBO}InfillCrit`.
In ParamHelpers for instance we have a function called `convertListOfRowsToDataFrame`.
We could shorten this one to `convListOfRowsToDataFrame` or `convertListOfRowsToDf`.
The latter should be fine, since there is `makeOptPathDF` instead of `makeOptPathDataFrame`.

**Comment by berndbischl** [comment]
i guess we are fine here too

**Comment by jakob-r** [comment]
thank god :raised_hands:
