### ISSUE TITLE
write blog post about mbo on mlr blog

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#365]

**Comment by jakob-r** [comment]
http://mlr-org.github.io/First_release_of_mlrMBO_the_toolbox_for_Bayesian_Black_Box_Optimization/

**Comment by berndbischl** [comment]
thx + cool post

but: can you please enable your spell checker? or read / check yourself?

having "Mu*lit*-Criteria" in these things on the list on the 1st page is a bit embarassing....
