### ISSUE TITLE
Discrete parameters

### ISSUE THREAD

**Issue by learnmower** [mlr-org/mlrMBO#368]
I am trying to use regr.xgboost with mlr/mlrMBO. Specifically, I would like to tune between dart and gblinear for booster. When trying to make parameter, I see that the discrete parameter calls the following to appear:

'''  if (hasDiscrete(par.set) && !hasLearnerProperties(learner, "factors"))
    stop("Provided learner does not support factor parameters.")'''

Does mlrMBO not support use of discrete parameters?

**Comment by ja-thomas** [comment]
mlrMBO does support mixed space optimization / discrete parameters. Have a look here: https://cran.r-project.org/web/packages/mlrMBO/vignettes/mixed_space_optimization.html

The learner you want to use does in fact not support discrete parameter spaces, so I would guess the dataset you are using has discrete parameters?

**Comment by berndbischl** [comment]
@learnmower post a minimal example, that shows where you get stuck?

**Comment by berndbischl** [comment]
@learnmower 
we have tried also to construct a reasonable default learner for such cases. in yours it would be a randomForest. Reopen with example if you have more problems
