### ISSUE TITLE
Plotting of first iteration for example is confusing

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlrMBO#371]
Complete code:

```
obj.fun = makeCosineMixtureFunction(1)
obj.fun = convertToMinimization(obj.fun)
control = makeMBOControl()
control = setMBOControlTermination(control, iters = 15)
control = setMBOControlInfill(control, crit = makeMBOInfillCritEI())

surr.km = makeLearner("regr.km", predict.type = "se", covtype = "matern3_2", control = list(trace = FALSE))
run = exampleRun(obj.fun, learner = surr.km, control = control, show.info = FALSE)

plotExampleRun(run)
```

The first iteration looks like this:

![first](https://cloud.githubusercontent.com/assets/579233/23987555/6d9ed6aa-0a2a-11e7-9443-4d2ce47efb3b.png)

There are evaluated points available, but the surrogate model doesn't consider them at all and has uniform EI over the entire space, making the choice of the first point to evaluate after that random. The data is taken into account only in the next iteration.

This doesn't look right to me. Shouldn't the first proposed point be based on the surrogate model from the initial data?

**Comment by ja-thomas** [comment]
That's not because it's the first iteration, but rather that surrogate model becomes constant from time to time. See here: #258

**Comment by ja-thomas** [comment]
It happens less frequent when we use `rgenoud` instead of `BFGS` to optimize the likelihood of the surrogate, which is why we use that in `makeMBOLearner()`

**Comment by larskotthoff** [comment]
Ok, but this is really weird. I got this behaviour several times with different initialisation points and it always disappeared in the second iteration. Is it the number of initial points that's the problem?

**Comment by ja-thomas** [comment]
Could be, we know that it also tends to happen in later iterations, especially for (highly) multi-modal / difficult functions

**Comment by larskotthoff** [comment]
Ok, thanks for the clarification!
