### ISSUE TITLE
the package file size is very large due to docs / pics

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#373]
this makes install slower than it must be
that also creates NOTES on cran

i am unsure if we want that.

we could put the vignetter in Rbuildignore and only host this on github
probably better

**Comment by jakob-r** [comment]
We don't have to put it into Rbuildignore. Subdirectories in vignettes/ are the recommended solution. 
The size is large because pkgdown outputs the pngs in retina resolution. Can probably changed so svg or not so high res png pictures.

**Comment by berndbischl** [comment]
> Subdirectories in vignettes/ are the recommended solution

if CRAN produces a NOTE we certainly do not use the "recommended" solution

**Comment by berndbischl** [comment]
and the subdir thing has nothing to do with what i wrote here? 

it is simply about whether we want all users always to install our anims and pics. and whether we can ever get that to a smaller size.

**Comment by jakob-r** [comment]
If you checked carefully you would see that the animation for example is not part of the build as it is in a subdirectory of vignettes. 
As i was saying the large size is just due to the high res pngs.

So all i am saying is that we have the following options:

1) We could simply move all additional vignettes into a sub directory 
2) We could probably generate smaller pngs
3) We could probably generate svgs

**Comment by jakob-r** [comment]
I changed everything to SVG graphics except noisy is set to png and low res for vignette only.

tar.gz: 3.9 MB -> 2.3 MB
extracted inst/doc: 7.4 MB -> 5.9 MB

Still big but I don't see a reason to fight that hard to be able to get the package on a floppy disk.

**Comment by berndbischl** [comment]
i dont know. i see this as low prio, but i dont like this. 

imagine if everybody would do this. 

PH contains also plotting functions. PH is on cran of 26kb. the code complexity is also somewhat comparable. now what PH is missing, severely missing, is a good vignette.
so it now becomes 5 mb?

and everybody else does the same? and update packages now downloads a few gigabytes?

**Comment by jakob-r** [comment]
I get your point. I still think you can hardly compare a package that is a dependency for many others to a package that usually only "sits on top" of everything. But on the other hand: We have the github page and who is looking at a vignette anyways when there is the github page: so i think i will just move everything except the quickintro into a sub directory.

**Comment by berndbischl** [comment]
i mean i LIKE that the vignette is visible an CRAN.

lets have a "stub" there which clearly explains where the REAL stuff is?

travis does all of the checking for us? and CRAN does not help more with that?
so that is win-win-win for all?

**Comment by jakob-r** [comment]
I guess you should open an issue for batchtools: https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/batchtools-00check.html :wink: 
A "big" problem is the javascript stuff in those pkgdown vignettes.
