### ISSUE TITLE
do NOT use assertInt or asserIntegerish

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#374]
the idiom should be

i = asInt(i)

at least for assertInt users will other get error when they enter 1 instead of 1L

grep over code and fix

**Comment by jakob-r** [comment]
Can you post an example, where `assertInt(1)` or `assertIntegerish(1)` raises an error?

**Comment by berndbischl** [comment]
has @mllg changed that? it did a few hours ago in one of my examples.

also i dont get this. if assertInt(1) passes what is the need then for assertIntegerish?

also note that assertInt(x) basically "lies". if x = 1, after that line, x is not an int.

**Comment by berndbischl** [comment]
here is actually the bug, I tried a wromg example!

```
load_all()
f = makeCosineMixtureFunction(1)
ctrl = makeMBOControl()
ctrl = setMBOControlTermination(ctrl, iters = 1)
r = exampleRun(f, control = ctrl)
pls = renderExampleRunPlot(r, iter = 1)
```

 Assertion on 'iter' failed: Must be of type 'integer', not 'double'.

**Comment by berndbischl** [comment]
cool, assertInt and assertInteger have different behavior.....

assertInt(1) works, assertInteger(1) does not... :(

**Comment by jakob-r** [comment]
So what we want in mlrMBO is replace assertInteger with assertIntegerish. I will do now.

**Comment by berndbischl** [comment]
> So what we want in mlrMBO is replace assertInteger with assertIntegerish. I will do now.

no. reread the thread. we want asInt.

that is also the standard in all other packages

**Comment by jakob-r** [comment]
Okay. I am fine with saving those bytes.

**Comment by jakob-r** [comment]
What would you say if we remove all L integers (as many as possible) from the tests to make sure this does not happen to the end user.

**Comment by berndbischl** [comment]
> Okay. I am fine with saving those bytes, although that type conversion costs us some time

@jakob-r when you want to optimize time efficiency of ANY of our packages, I can point you to about a dozen places where it REALLY makes sense and we would gain something.....
come on

> What would you say if we remove all L integers (as many as possible) from the tests to make sure this does not happen to the end user.

i dont know. My gut feeling says I would hate that. Our style is rather to use 1L instead of 1. Which is good and correct. Now we deviate from this, but just in the tests? And people who correctly use the 1L are now being corrected, in the tests? That sounds VERY confusing.....

I would not worry THAT much here. I dont think we have a LARGE problem. IMHO I would simply like to become cm a bit more "intuitive" and beautiful here. 
Maybe I overreacted a bit, I mainly care about the last sentence. Also the bug does really not hurt you THAT much (if you know R)
