### ISSUE TITLE
do not supported on windows ?

### ISSUE THREAD

**Issue by yunxileo** [mlr-org/mlrMBO#384]
run: parallelStartMulticore(cpus =4L) 
Error in parallelStart(mode = MODE_MULTICORE, cpus = cpus, level = level,  : 
 Multicore mode not supported on windows!

**Comment by ja-thomas** [comment]
Multicore utilizes the parallel package which only runs on Linux (and Mac).

If you want to parallelize on Windows use `parallelStartSocket(cpus = 4L)`.

Also, this has nothing to do with mlrMBO but is a functionality in parallelMap: https://github.com/berndbischl/parallelMap

Have a look at the documentation there on how to parallelize code on windows.

**Comment by yunxileo** [comment]
Thanks for  help!
