### ISSUE TITLE
Need tutorial example with real model on iris dataset or the like

### ISSUE THREAD

**Issue by Prometheus77** [mlr-org/mlrMBO#385]
I'm trying to use mlrMBO to optimize hyperparameters of modeling techniques such as knn, xgboost, svm, etc. It's not clear to me from the documentation examples what the right syntax is to set up such an optimization problem. All of the examples in the tutorial use smoof functions rather than actual models. Is there a tutorial example which shows how to build a real model on an actual dataset such as iris? This would be extremely helpful for new users.

**Comment by berndbischl** [comment]
1) you correct, we need a mini vignette for this

2) there are 2 approaches. 

a) call MBO on your own objective functions, which simply resamples a models. thats a bit manual, but works exactly as it documented for all other functions. simply create your objective like this.

b) easier: use mlr::makeTuneControlMBO

as it is too late now, let me add more details later

@ja-thomas @mllg  @jakob-r 

this is super important that we finish this. can someone help?

**Comment by jakob-r** [comment]
Hi,
it's covered but not explicitly. In each Topic (except parallelization) we use functions that are not taken from `smoof`, but you are right in the sense that you have to wrap your function in a smoof function. This is because an R function itself does not contain information about the search space and other properties of the function.

**Comment by Prometheus77** [comment]
This ended up being just the jumpstart I needed. Looks like you've Incorporated it into GitHub, if not the tutorial.
http://mlr-org.github.io/How-to-win-a-drone-in-20-lines-of-R-code/
