### ISSUE TITLE
Restructure tutorial 

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#39]
I started to restructure the tutorial. Going to work on it this week.

**Comment by jakob-r** [comment]
We will first focus on a good readable paper with exemplary code that we can add as a vignette

**Comment by berndbischl** [comment]
not if we submit to rjournal, then the paper could be the vignette

**Comment by jakobbossek** [comment]
Closing. We have tutorial related issues #232, #233.
