### ISSUE TITLE
mbo does not work with smoof logging wrapper - bad arg check

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#393]
tf = makeBraninFunction()
ctrl = makeMBOControl()                                                                                                                                           
ctrl = setMBOControlTermination(ctrl, max.evals = 10)                                                                                                   
tf = addLoggingWrapper(tf)                                                                                                                                        
r = mbo(fun = tf, control = ctrl)                                                                                                                                 

 Assertion on 'fun' failed: Must have class 'smoof_function', but has classes 'smoof_logging_function','smoof_wrapped_function'.

**Comment by jakob-r** [comment]
I also already stumbled upon that. I think as you wrote it should be smoof_function as well. Then we can leave things here unchanged. Waiting for @jakobbossek opinion.

**Comment by jakobbossek** [comment]
Fixed in dev version of smoof. We do not need to change anything. However, we should not close and imports smoof (>= 1.5.1) as soon as it is released on CRAN.

**Comment by berndbischl** [comment]
we should add a use case test here, then close

**Comment by jakobbossek** [comment]
smoof v1.5.1 is on CRAN now. mlrMBO now depends on this version.

**Comment by jakob-r** [comment]
Do we need a test or can we simply close?

**Comment by berndbischl** [comment]
> we should add a use case test here, then close

**Comment by jakob-r** [comment]
Okay. We have this in #394
