### ISSUE TITLE
Mbo mutlicrit evaluations

### ISSUE THREAD

**Issue by aminevsaziz** [mlr-org/mlrMBO#395]
I've been testing mlrmbo for quite of time now to tune some learners,however is it possible to implement  multicrit of 2 metric for example to tune a simple svm,If yes a minimal example would be helpful as starting point.

**Comment by ja-thomas** [comment]
Hi @aminevsaziz 

It is relatively easy to change one of the example in the vignette to use multicrit optimization. But we should add a separate topic for multicrit tuning.

```
library(mlrMBO)
library(mlr)

configureMlr(on.learner.warning = "quiet", show.learner.output = FALSE)

iters = 5

par.set = makeParamSet(
  makeNumericParam("cost", -15, 15, trafo = function(x) 2^x),
  makeNumericParam("gamma", -15, 15, trafo = function(x) 2^x)
)

svm = makeMultiObjectiveFunction(name = "svm.tuning",
  fn = function(x) {
    lrn = makeLearner("classif.svm", par.vals = x)
    resample(lrn, iris.task, cv3, measures = list(mmce, timetrain), show.info = FALSE)$aggr
  },
  par.set = par.set,
  has.simple.signature = FALSE,
  minimize = c(TRUE, TRUE),
  n.objectives = 2L
)

ctrl = makeMBOControl(n.objectives = 2L)
ctrl = setMBOControlTermination(ctrl, iters = iters)
ctrl = setMBOControlInfill(ctrl, crit = crit.dib1)
res = mbo(svm, control = ctrl, show.info = FALSE)
```
This example is the same as the one in the vignette  (https://mlr-org.github.io/mlrMBO/articles/supplementary/machine_learning_with_mlrmbo.html) but minimizes the MMCE and train time. For further configuration see `?setMBOControlMultiObj`

**Comment by aminevsaziz** [comment]
@ja-thomas  i will try your example as soon as i get home...but is it possible  to use mlr interface instead of initiating  a smoof function for muti-objective tuning?

**Comment by ja-thomas** [comment]
This is currently not supported. We have an issue for that here https://github.com/mlr-org/mlr/issues/1007 and a partially done PR https://github.com/mlr-org/mlr/pull/1073/

**Comment by aminevsaziz** [comment]
@ja-thomas too bad that is not supported yet :( ...however i am aiming at benchmark experiment with nested resampling for some learners ,so according to your example @ja-thomas  i fine tune each learner separately using multiobjective function then feed the opt parameters to another train function.
P.S: why did you use dib1as infill instead of cb or ei

**Comment by aminevsaziz** [comment]
@ja-thomas  i tested your codes it work perfectly thank you for your help..however im facing other issues check #396 so  if you can help that would be appreciable .

**Comment by jakob-r** [comment]
multicrit mbo is now part of mlr (github version)
