### ISSUE TITLE
Make tuning reproducible

### ISSUE THREAD

**Issue by PhilippPro** [mlr-org/mlrMBO#402]
Is there a way to make the tuning process in mlrMBO reproducible? Currently I always get different results, because there is no option for setting a seed in the randomization functions...

Setting a seed before executing `mbo` doesn't help to get exactly the same results.

**Comment by PhilippPro** [comment]
Example: 

```
library(mlr)
ps = makeParamSet(
  makeNumericParam("C", lower = -12, upper = 12, trafo = function(x) 2^x),
  makeNumericParam("sigma", lower = -12, upper = 12, trafo = function(x) 2^x)
)
library(mlrMBO)
control = makeMBOControl(n.objectives = 1L, propose.points = 1)
control = setMBOControlTermination(control, max.evals = 100, iters = 100)
set.seed(130)
design = generateDesign(30, ps, fun = lhs::maximinLHS) 
ctrl = makeTuneControlMBO(mbo.control = control, mbo.design = design)
rdesc = makeResampleDesc("Holdout")
set.seed(123)
res = tuneParams(makeLearner("classif.ksvm"), task = sonar.task, resampling = rdesc, par.set = ps,
  measures = list(mmce), control = ctrl, show.info = FALSE)
res$x
set.seed(123)
res = tuneParams(makeLearner("classif.ksvm"), task = sonar.task, resampling = rdesc, par.set = ps,
  measures = list(mmce), control = ctrl, show.info = FALSE)
res$x
```

**Comment by jakob-r** [comment]
This is a problem of the `rgenoud` optimizer that is used for the likelihood maximization. I already wrote the authors to use the r seed value but I don't know when this will be the case. I think I will switch to the BFGS optimizer which was not that good but at least is reproducible. 
What you can do is to create the surrogate learner manually:
```r
mbo.lrn = makeLearner("regr.km", covtype = "matern3_2", optim.method = "BFGS", nugget.estim = TRUE, jitter = TRUE)
ctrl = makeTuneControlMBO(mbo.control = control, mbo.design = design, learner = mbo.lrn)
```

**Comment by PhilippPro** [comment]
What does mean "not that good"? Does it make a big difference?

**Comment by berndbischl** [comment]
> What does mean "not that good"? Does it make a big difference?

we benchmarked this internally, at least a bit, but these results are not in the paper. 

at the moment we cannot do much about this as this problem is completely internal in another package. 
and we have a general issue about the topic now here, #404, so this is dupllicated.

and you have an easy way to fix on your side: simply switch to BFGS.

**Comment by jakob-r** [comment]
>https://github.com/mlr-org/mlrMBO/issues/258

Not so much, see the comparison given here: https://github.com/mlr-org/mlrMBO/issues/258

**Comment by berndbischl** [comment]
> What does mean "not that good"? Does it make a big difference?
> Not so much, see the comparison given here: #258

contact @ja-thomas if you want a proper benchmark, he still has the data

**Comment by pat-s** [comment]
I just came across this. Shouldn't this either be changed so that BFGS is the default or a least strongly documented? Having this in an issue "only" seems kinda hidden for such an important point.

**Comment by jakob-r** [comment]
As you can see in #404 it is already fixed
