### ISSUE TITLE
use `saveRDS` instead of `save`

### ISSUE THREAD

**Issue by zkurtz** [mlr-org/mlrMBO#405]
`makeMBOControl` involves setting `save.file.path` for saving the output of a run.  Currently `mlrMBO` is saving via `save`, [but some (including my self) prefer `saveRDS`](https://csgillespie.github.io/efficientR/efficient-inputoutput.html#efficient-data-export-.rdata-or-.rds). For one thing, you then have the option of loading with assignment like `x = loadRDS(file)` without having to guess at the name of the object that `load(file)` might be putting in your environment.

**Comment by jakob-r** [comment]
This is a good point and I prefer RDS as well. Unfortunately making this change would break compatibility with old saved results which makes me hesitant.

**Comment by zkurtz** [comment]
Fair enough!  Not a big deal of course.

**Comment by jakob-r** [comment]
We also have BBmisc::load2 which kind of avoids to load unwanted things in your namespace for the price that you have to know the name of the object in the RData file you want to load.
