### ISSUE TITLE
Bug in ParEGO + EI

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#407]
There is a bug in ParEGO using EI as the infill criteria. In ParEGO, the model is fitted to a scalarized version of multiple objetives. We do this correctly - the fitting of the model. However, in the calculation of the EI there is this tiny y_min. Here, we should use the minimal value of the scalarized objectives. What we do: We use the minimal value of the unscalarized objectives. You can see in this example, where Marius Greiff from Günther Rudolphs chair added a print inside mlrMBO:

```r
library("mlrMBO")
# CRAN-Version of mlrMBO with print(y) behind y = maximize.mult * design[, control$y.name]
# in the funkcion makeMBOInfillCritEI 

set.seed(1)

f  = makeMultiObjectiveFunction(name = "",
  fn = function(x) c(-x, x^2),
  par.set = makeNumericParamSet("x", 1L, -10L, 10L),
  n.objectives = 2)
des = generateDesign(n = 5, par.set = getParamSet(f), fun = lhs::randomLHS)
surr.km = makeLearner("regr.km", predict.type = "se", covtype = "matern5_2")
setHyperPars(surr.km, multistart = 1)

control = makeMBOControl(n.objectives = 2L, propose.points = 1)
control = setMBOControlTermination(control, iters = 1)
control = setMBOControlMultiObj(control, method = "parego")
control = setMBOControlInfill(control, crit = makeMBOInfillCritEI(),
  opt.focussearch.maxit = 1, filter.proposed.points = FALSE)

run = mbo(f, design = des, learner = surr.km, control = control, show.info = FALSE)
# print(y): 
#          y_1       y_2
# 1 -9.5935587 92.036369
# 2  6.2212989 38.704560
# 3  3.3568088 11.268166
# 4 -0.5164562  0.266727
# 5 -2.2471451  5.049661

# y should have only 1 column here, but it has 2

```

This seems to be a design error of our code. Inside the infill-crit function we do not have access to the acces to the scalarized objective values. The design should have an additional column for the scalarized values, and control$y.name must be set to this column. This could be done in proposePointsParEGO. However, the scalarized values are only calcuated in makeTasksParEGO and added to the regr.tasks, so they are not know in proposePointsParEGO. To be honest, I have no idea how we could fix this in a clean way (of course, quick and dirty is allways possible).

I fear that all bad results of EI-ParEGO of our past benchmarks are consequences of this bug...

**Comment by jakob-r** [comment]
I've created a not so ugly fix (but also not perfect). Please have a look.

**Comment by mariusgreiff** [comment]
I tried your fix for this issue with my code from above:
```{r}
library("devtools")
install_github("mlr-org/mlrMBO", ref = "fix407_scalarize_parego_infill", force = TRUE)
library("mlrMBO")

set.seed(1)

f  = makeMultiObjectiveFunction(name = "",
                                fn = function(x) c(-x, x^2),
                                par.set =
makeParamSet(makeNumericVectorParam("x",
len = 1L, lower = -10, upper = 10)),
                                n.objectives = 2)
des = generateDesign(n = 5, par.set = getParamSet(f), fun = lhs::randomLHS)
surr.km = makeLearner("regr.km", predict.type = "se", covtype = "matern5_2", control = list(trace = FALSE))
setHyperPars(surr.km, multistart = 1)

control = makeMBOControl(n.objectives = 2L, propose.points = 1)
control = setMBOControlTermination(control, iters = 1)
control = setMBOControlMultiObj(control, method = "parego")
control = setMBOControlInfill(control, crit = makeMBOInfillCritEI(),
opt.focussearch.maxit = 1, filter.proposed.points = FALSE)

run = mbo(f, design = des, learner = surr.km, control = control, show.info = FALSE)
```
and got the following error message:
Error in diag(control$n.objectives)[control$multiobj.parego.use.margin.points,  :  (subscript) logical subscript too long.

In my opinion the easiest way to fix the bug is to only scalarize y in
proposePointsByInfillOptimization.R and to add something like
control2$y.name = "y_scalar" to proposePointsParEGO.R. You can find an
example for this in 306a31a.
I'm not sure if my normalization is correct.

**Comment by jakob-r** [comment]
Should be fixed now.
