### ISSUE TITLE
[Question] Is there a way to save also during the design?

### ISSUE THREAD

**Issue by maxime-petit** [mlr-org/mlrMBO#410]
Hi,

I wanted to know if there is a way to save the mbo during the design evaluation step? I managed to save using save.on.disk.at parameters, but the save only begin when the design is done (same thing for save.on.disk.at.time).

Is there a simple way to save also the evaluation during the design generation, in order to recover if a problem occurs during it? Is it then possible to use the continue method, or it is only possible after the design evaluation?

Thank in advance

**Comment by jakob-r** [comment]
Currently there is no way. So you would have to pre evaluate the Design yourself and make sure to make it robust against failures. 

Here is some code that could help:
https://github.com/jakob-r/mboBench/blob/1bf8635fa89b2b1c51ebb71534baa7a0c5a4a174/R/evalDesign.R
Needs `purrr`, `ParamHelpers`, `smoof` and `parallelMap` I guess.
