### ISSUE TITLE
What if obj function is a system?

### ISSUE THREAD

**Issue by chaseblack** [mlr-org/mlrMBO#419]
I am tuning a system which has several params.  I don't think I can provide an analytical function to be optimised. How to cope with this case?

**Comment by chaseblack** [comment]
Thanks for your reply! Well, I am new to R so maybe I asked the not-wise question. I read from the doc that "Objective functions are created with package smoof", then I went to spoof, it shows me the creation of a smoof function like this:

obj.fn = makeSingleObjectiveFunction(
  name = "My fancy function name",
  fn = function(x) x * sin(3*x),
  par.set = makeNumericParamSet("x", len = 1L, lower = 0, upper = 2 * pi)
)

Therefore I thought the obj function could only be written in an analytical way. 
However, in my case, MBO suggests a new input, after that system gives an output which is stored in a file. So I wanted to create an obj function that read the file and get the feedback(or output). Could you please tell me how can I do this?

**Comment by jakob-r** [comment]
This really only serves as an example. The `fn` part of the smoof function can be any arbitrary function.
Maybe this blog post helps:

http://mlr-org.github.io/Use_mlrMBO_to_optimize_via_command_line/

**Comment by chaseblack** [comment]
Hi @jakob-r, thank you a lot! I think this is the blog that I need.
