### ISSUE TITLE
Error in predict.randomForest(.model$learner.model, newdata = .newdata,  : missing values in newdata Calls: mbo ... predictLearner.regr.randomForest -> predict -> predict.randomForest

### ISSUE THREAD

**Issue by chaseblack** [mlr-org/mlrMBO#422]
Well, I am writing a very simple categorical param tuning. There is the code:
myOpt.R:
```
runScript = function(x) {
  runif(1, 5.0, 7.5)
}
library(mlrMBO)
params=readLines("params4BayOpt.csv")
vals=readLines("vals4BayOpt.csv")
paramSet=list()
for(i in 1:length(params)){
 paramSet[[i]]=makeDiscreteParam(params[i], values=vals)
}
par.set = makeParamSet(params=paramSet,forbidden = NULL, keys = NULL)
fn = makeSingleObjectiveFunction(
  id = "fun.sh",
  fn = runScript,
  par.set = par.set,
  has.simple.signature = FALSE
)
des = generateDesign(n=10,par.set=getParamSet(fn),fun = lhs::maximinLHS)
ctrl = makeMBOControl(n.objectives=1L,propose.points=1L)
ctrl = setMBOControlInfill(control=ctrl, opt="focussearch", crit = crit.ei,opt.focussearch.points=500)
ctrl = setMBOControlTermination(ctrl, iters = 1)
learner=makeMBOLearner(control=ctrl,fun=fn,ntree=500)
configureMlr(show.info = TRUE, show.learner.output = TRUE)
run = mbo(fun = fn, design=des, learner=learner, control = ctrl)
```
Basically,  basically it first defines a function and the params are loaded from file. One file is params4BayOpt.csv which is just the param name, one is vals4BayOpt.csv, which is all possible categorical values that each param can take. 
params4BayOpt.csv:
x1
x2
x3
x4
x5
x6
x7
x8
x9
x10
x11
x12
x13
x15
vals4BayOpt.csv:
A
B
C
D
E
F
G
H
I
J
K
L
M
N

 When I run this using **Rscript myOpt.R**, it shows the following error:
```
Warning in makeTask(type = type, data = data, weights = weights, blocking = blocking,  :
  _Empty factor levels were dropped for columns: x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x15
Error in predict.randomForest(.model$learner.model, newdata = .newdata,  :
  missing values in newdata
Calls: mbo ... predictLearner.regr.randomForest -> predict -> predict.randomForest
Execution halted_
```
But the interesting thing is when I decrease the param number and values like shown in the following, the script works! 

params4BayOpt.csv:
x1
x2
x3
x4
x5
x6
x7
x8
x9
x10
vals4BayOpt.csv:
A
B
C
D
E
F

I can not figure out why, any suggestions? Thanks in advance!!

**Comment by chaseblack** [comment]
Hi I changed the code and do not let the script read params from files. The full code is:

**runScript = function(x) {
  runif(1, 5.0, 7.5)
}
library(mlrMBO)
par.set = makeParamSet(
makeDiscreteParam("x1", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x2", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x3", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x4", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x5", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x6", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x7", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x8", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x9", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x10", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x11", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x12", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x13", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x14", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o")),
makeDiscreteParam("x15", values = c("a", "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o"))
)

fn = makeSingleObjectiveFunction(
  id = "fun.sh",
  fn = runScript,
  par.set = par.set,
  has.simple.signature = FALSE
)

des = generateDesign(n=15,par.set=getParamSet(fn),fun=lhs::maximinLHS)
par.set=getParamSet(fn), fun = lhs::randomLHS))
ctrl = makeMBOControl(n.objectives=1L,propose.points=1L)
ctrl = setMBOControlInfill(control=ctrl, opt="focussearch", crit = crit.ei,opt.focussearch.points=500)
ctrl = setMBOControlTermination(ctrl, iters = 1)
learner=makeMBOLearner(control=ctrl,fun=fn,ntree=500)
configureMlr(show.info = TRUE, show.learner.output = TRUE)
run = mbo(fun = fn, design=des, learner=learner,control = ctrl)**

And the error is:

**Warning in makeTask(type = type, data = data, weights = weights, blocking = blocking,  :
  Empty factor levels were dropped for columns: x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15
Error in predict.randomForest(.model$learner.model, newdata = .newdata,  :
  missing values in newdata
Calls: mbo ... predictLearner.regr.randomForest -> predict -> predict.randomForest
Execution halted**

Any suggestions?

**Comment by jakob-r** [comment]
On the one hand that error should not happen. On the other hand it's a very hard optimization problem because of the many factor levels. If you can assume that the values are ordered, then I would recode them to numbers before doing the optimization.

**Comment by chaseblack** [comment]
Hi, thanks for your reply. Maybe I should check if they can be ordered.

**Comment by Automatik** [comment]
I know this issue is closed, but for anyone else encountering this I solved it by increasing the number of points in method `generateDesign`

Quoting from this [issue](#454 )

> Your initial design has to contain each discrete value at least once so that the surrogate can make predictions.
