### ISSUE TITLE
Documentation page seems to have missing images

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlrMBO#428]
The [Documentation](https://mlr-org.github.io/mlrMBO) seems to have pages with missing images, for example https://mlr-org.github.io/mlrMBO/articles/mlrMBO.html which looks like the following on my machine:
![missing](https://user-images.githubusercontent.com/15801081/40720371-c54976d4-6416-11e8-9d41-2a9376f7a15e.png)

(On two desktops, and on my phone using mobile data, the images are missing, but archive.is shows the images, so I don't know if this is github's fault or something temporary)

**Comment by jakob-r** [comment]
Probably a changed build process. Thanks for pointing it out.

**Comment by jakob-r** [comment]
This was solved by using pngs.
