### ISSUE TITLE
Default of opt.restarts is wrong

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlrMBO#432]
It is documented as 3 (in the code as well as the paper)

but actually set to 1.

**Comment by jakob-r** [comment]
So what now?

1) fix doc
2) fix default

I vote for 1)

**Comment by berndbischl** [comment]
> I vote for 1)

that does not work. unless you dont also volunteer to rerun all exps in the paper, and reupload to arxiv....


so we have to fix the number simply in the code, i guess.
correct, @ja-thomas ?

**Comment by ja-thomas** [comment]
No, I just checked the benchmark code, we set the focussearch parameters explicitly so the benchmarks (except the new multiobj benchmark) are correct and we can got for 1)

**Comment by berndbischl** [comment]
shall we just update 1 character now and close this?

**Comment by ja-thomas** [comment]
pushed (directly to master)

**Comment by ja-thomas** [comment]
nargs, that why one shouldn't push to master..

this breaks the R:devel for some reason, I can't reproduce locally....

**Comment by ja-thomas** [comment]
fixed :)
