### ISSUE TITLE
regression h2o deep learning 

### ISSUE THREAD

**Issue by Hadsga** [mlr-org/mlrMBO#434]
I found two issues regarding the mlrMBO package. 

1. MlrMBO seems not to support tuning the activation function. If I look at the [documentation](https://rdrr.io/cran/mlr/src/R/RLearner_regr_h2odeeplearning.R) it should work.  

```
lrn_dl <- makeLearner("regr.h2o.deeplearning")

dl_param <- makeParamSet(
  makeDiscreteParam("activation", values = c("Rectifier", 
                                             "Tanh",
                                             "TanhWithDropout", 
                                             "RectifierWithDropout", 
                                             "Maxout", 
                                             "MaxoutWithDropout")),
  makeIntegerVectorParam("hidden", len = 2, lower = 20, upper = 200), 
  makeIntegerParam("epochs", lower = 1, upper = 100),
  makeNumericParam("l1", lower = 1e-6, upper = 1e-1),
  makeNumericParam("l2", lower = 1e-6, upper = 1e-1))

mbo.ctrl <- makeMBOControl()
mbo.ctrl <- setMBOControlTermination(mbo.ctrl, iters = 10)
surrogate.lrn <- makeLearner("regr.km", predict.type = "se")
ctrl <- makeTuneControlMBO(learner = surrogate.lrn, mbo.control = mbo.ctrl)

rdesc <- makeResampleDesc("CV", iters = 10)


set.seed(3)
dl_tune <- tuneParams(learner = lrn_dl, 
                      par.set = dl_param,
                      task = train_task, 
                      resampling = rdesc,
                      control = ctrl, 
                      show.info = TRUE, 
                      measures = list(mse, rsq))

Error in checkStuff(fun, design, learner, control) : Provided learner does not support factor parameters.
```

If I specify it in the `makeLearner` function it works (e.g.): 

`lrn_dl <- makeLearner("regr.h2o.deeplearning", par.vals = list(activation = "Tanh")`

2. It would be nice if I could tune the hidden layers with a different length. But I didn´t find a solution to change the the lenght in `makeIntegerVectorParam` which means I can just tune the number of hidden layers but not the length:

`makeIntegerVectorParam("hidden", len = 2, lower = 20, upper = 200)`
or
`makeIntegerVectorParam("hidden", len = 3, lower = 20, upper = 200)`
`
etc. works ... but not this one:

`makeIntegerVectorParam("hidden", len = 2:3, lower = 20, upper = 200)`

**Comment by jakob-r** [comment]
One problem is you are trying to tune a discrete search space. This does not work out of the box if you use Kriging. You can either chose a different surrogate (e.g. randomForest, ranger) or use wrappers:
```r
surrogate.lrn = makeImputeWrapper(lrn, classes = list(numeric = imputeMax(2), factor = imputeConstant("__miss__")))
surrogate.lrn = makeDummyFeaturesWrapper(lrn)
```

Tuning the number of hidden layers can be done if you write your own objective function for mlrMBO. Then you can just introduce a parameter (e.g. `n.hidden`) for the number of hidden layers. For `"hidden"` you just set eg. `len = 3`. In your custom objective function `n.hidden` just defines how many of `hidden` you really pass to the parameter values.

**Comment by berndbischl** [comment]
what jakob said is all good, but some more (maybe more convenient...) info:
just leave out the learner completely, if you dont know perfectly well what you are doing. 
we have smart defaults here, and mbo will create a default surrogate for you.
read:
?makeMBOLearner

**Comment by Hadsga** [comment]
Thanks for your replies. Deep learning and Bayesian Optimization are new to me. I need some time to understand both concepts in depth. 

PS: Keep up your great work. Mlr/mlrMBO are really awesome.
