### ISSUE TITLE
Contradiction in Noisy Optimization doc page

### ISSUE THREAD

**Issue by robsmith11** [mlr-org/mlrMBO#438]
There appears to be a contradiction here:

https://mlr-org.github.io/mlrMBO/articles/supplementary/noisy_optimization.html
"Kriging requires heteroscedasticity but slight dependencies of the variance on the x can be acceptable"

I'm guessing it was meant to say "requires homoscedasticity".  It would also be helpful to include which suragate, if any, should be used for cases with high heteroscedasticity.

**Comment by jakob-r** [comment]
You are absolutely right. Thanks for spotting this error. However I don't know of any special methods for heteroscedasticity.
