### ISSUE TITLE
Stronger enforcement needed for 'tunable = FALSE'?

### ISSUE THREAD

**Issue by zkurtz** [mlr-org/mlrMBO#445]
Even when I set a default value for a discrete parameter and set `tunable = FALSE`, the tuner still tries to tune on that parameter. Is this expected behavior? Of course I can force it not to tune by putting only the default value in the `values` list ... but then what is the point of `tunable`?

```
library(mlrMBO)
library(data.table)

fun = function(x) {
    if(x$method == "a"){
        out = sqrt(x$number)
    }else{
        out = x$number^2
    }
    if(is.na(out)){
        browser()
    }
    return(out)
}

space = makeParamSet(
    makeDiscreteParam("method", 
        values = c("a", "b"),
        default = "a",
        tunable = FALSE),
    makeNumericParam("number", lower = 0, upper = 2)
)

obj = makeSingleObjectiveFunction(
  name = "mixed_example",
  fn = fun,
  par.set = space,
  has.simple.signature = FALSE
)

run = mbo(obj, control = makeMBOControl(), show.info = FALSE)

# Observe that both method "a" and "b" got tested
table(as.data.table(run$opt.path)$method)
```

**Comment by jakob-r** [comment]
1) Yes it is expected.
2) The point of `tunable` is just meta information that we once thought was a good idea to have in mlr. This has actually nothing to do with mlrMBO and is not supposed and accounted for. Sorry for the confusion. I am a bit at a loss of where the best place would be to document this. Do you have any suggestion?

If you have fixed parameter for a function don't put it in the definition of the *tuning space* but use e.g. `more.args = list(method = "a")`

**Comment by zkurtz** [comment]
Ah, OK. Maybe the simplest thing is to slightly modify the current docstring: 

> Is this parameter tunable? Defining a parameter to be not-tunable allows to mark arguments like, e.g., “verbose” or other purely technical stuff, and allows them to be excluded from later automatic optimization procedures that would try to consider all available parameters. Default is TRUE (except for untyped, function, character and characterVector) which means it is tunable. 

How about instead:

> Is this parameter tunable? Describing a parameter as not-tunable is a way to document when arguments like “verbose” or other purely technical stuff should not be of interest to subsequent optimization procedures that may try to consider all available parameters. Default is TRUE (except for untyped, function, character and characterVector) which means it is tunable. Note that setting the value of `tunable` currently has no effect on the operation of `mlrMBO::mbo`. 

An alternative might be to deprecate `tunable` in its current form in favor of an automated procedure. I'm guessing it's easy to examine a ParamSet object to deduce where the specified range of each parameter admits more than one unique value, although this could get trickier in combination with `forbidden`.

**Comment by jakob-r** [comment]
Will open an issue in ParamHelpers then. Thanks.
