### ISSUE TITLE
add aei infill criterion exception in checkStuff for multipoint evaluation

### ISSUE THREAD

**Issue by RPdavies** [mlr-org/mlrMBO#458]
Dear developers,

In the vignette for multipoint-parallelisation it is clearly stated that the *constant liar* is a suitable method for proposing points when using either the *augmented expected* or the *expected improvement*. See line 67: https://github.com/mlr-org/mlrMBO/blob/7c4252492baad37e6d731e0a4725c11d86f2bd7d/vignettes/supplementary/parallelization.Rmd#L67

On the other hand, attempting to use *constant liar* with *augmented expected improvement* (**'aei'**), the below error is produced by *checkStuff*:

"Multi-point proposal using constant liar needs the infill criterion 'ei' (expected improvement), but you used 'aei'!"

Is this intentional, or should 'aei' be added to the exception list? As far as I understand there is no reason why 'aei' should not be a valid infill criterion for multipoint proposal. Furthermore, not being able to do so makes multipoint proposal for noisy functions impossible, which is a serious limitation.

Best regards,
Philip

**Comment by jakob-r** [comment]
You are totally right. I will include this in mlrMBO and hopefully soon in the CRAN version.

**Comment by jakob-r** [comment]
Should work now. Please let me now if you have other issues.

**Comment by RPdavies** [comment]
It works perfectly, thank you very much!
