### ISSUE TITLE
Include the time estimate

### ISSUE THREAD

**Issue by danielhorn** [mlr-org/mlrMBO#46]
We want to include the time aspect into both uni and multi crit, e.g. we want to have things like expected improvement per minute.
One special application: In multicrit: Include this while the time is one target function and while we want to propose multiple points -> here the time of one iteration is the maximum time of one of the proposed function evals.

We need to think about what we can do here.

**Comment by jakob-r** [comment]
Should not be so hard - I kind of did it already in my mfMBO part - but removed it for merging reasons. Have to implement it for another project nonetheless.

**Comment by berndbischl** [comment]
Please to it only for single crit first. This is most important now (and more importantly: clearer).

It is not a trivial issue. Discuss with us any questions that come up.

**Comment by berndbischl** [comment]
And thanks if you do this.

**Comment by jakob-r** [comment]
It is already integrated.
See `getOptStateTimeModel`. Usage is something like:
```r
time.model = getOptStateTimeModel(opt.state)
time.points = getPredictionResponse(predict(time.model, newdata = prop.points))
```
