### ISSUE TITLE
ability to relearn  parameters

### ISSUE THREAD

**Issue by asheetal** [mlr-org/mlrMBO#462]
Would be  nice  to dump the  history  of past parameters. Trying to restart the tuning  after a powerloss  is painful. Would be nice to call a function periodically  that  would dump the past parameters and y values and then inject them back in case of power loss.

**Comment by berndbischl** [comment]
sure.
but did you read ?makeMBOControl?

the history is stored in the optpath object. and that can be periodically saved

```
save.on.disk.at | [integer] Sequential optimization iteration when the actual state should be saved on disk. Iteration 0 denotes the initial design. If the optimization stops with an crucial error, it can be restarted with this file via the function mboContinue. Default is integer(0L), i. e., not to save.
-- | --
```


Reopen if this does not help

**Comment by asheetal** [comment]
Thanks for the help. I tried to use this option with some code i  found in internet. 
ctrl = makeMBOControl(save.on.disk.at  = c(20,40,80,100,120,140,160,180,200,220,240,260,280,300),
					  output.num.format = "%.6g")

Maybe I did not understand the guide clearly,  but the  independent process that is generating the bayesian parameters stopped saving  12 hours ago (possibly at 300th iteration), while the model builder is on its 2000th iteration. The  two are separate processes and do not know each other's state. 

Did I pass the parameters wrong?

**Comment by RPdavies** [comment]
argument "save.on.disk.at" controls on which iterations the results are saved. In your example you have set save.on.disk.at = c(20,40,80,100,120,140,160,180,200,220,240,260,280,**300**), which means you would expect the final state that is saved to be iteration 300.

To keep saving every 20 iterations do something like save.on.disk.at = seq(1, total_itr, 20), where total_itr = the total number of iterations you wish to execute.

**Comment by asheetal** [comment]
It is hard for me to estimate how many total iterations would be executed. The goal is the target loss number. The models are run  on 4 parallel independant VGA cards  forked out. Any way I  can tell the mlrMBO to save every 60 seconds until it is stopped ^C  ?

**Comment by RPdavies** [comment]
I can't really help with that though as a quick fix if you set it to a very high number you should be able to keep on saving regularly for the whole duration.

**Comment by asheetal** [comment]
ok. Thanks. Will just  put a huge number for now.

**Comment by jakob-r** [comment]
Check the help of `?makeMBOControl` there you will find `save.on.disk.at.time` where you can set a time intervall when things should be saved to disk e.g. 300 for all 5 minutes.

**Comment by berndbischl** [comment]
Does this close the issue for real?

**Comment by asheetal** [comment]
yes. i now have a workaround and I pass a very long vector to save.on.disk.at. Thank  You.

**Comment by jakob-r** [comment]
@asheetal See my answer above. You actually do not need that workaround.

**Comment by asheetal** [comment]
I  had tried save.on.disk.at.time = 3600. That probably  has some issue with linux piping. 
I  run the script as follows
nohup ./model.R >& nohup.log&

The save.on.disk.at.time pipes the Rdata to nohup.log  and corrupts the nohup.log file. So for the moment I can only use save.on.disk.at

**Comment by pat-s** [comment]
> The save.on.disk.at.time pipes the Rdata to nohup.log and corrupts the nohup.log file.

This shouldn't be the case. Can you share a reprex?

Alternatively, you can use `byobu` instead of `nohup`.
