### ISSUE TITLE
animation vignette is broken

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlrMBO#467]
@jakob-r I discovered this when trying to build the pkgdown site.

Specifically, in

https://github.com/mlr-org/mlrMBO/blob/38133a679393465e9cb6be8e6437c3d7df9d5202/inst/animation.Rmd#L21-L22

`knitr:::sans_ext()` does not exist anymore. However, even when commenting this line, I get another error down the line.

I moved the Rmd to /inst for now.

**Comment by jakob-r** [comment]
Changed the animation to gifski and imgur upload of the generated gif.
How do I have to configure tic to deploy the README.Rmd?

**Comment by pat-s** [comment]
Thanks.

> How do I have to configure tic to deploy the README.Rmd?

I saw the issue first. Seems to have resolved itself in the meantime?

**Comment by jakob-r** [comment]
Works well enough.
