### ISSUE TITLE
setMBOControlTermination lists wrong(?) parameter type

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlrMBO#470]
https://mlrmbo.mlr-org.com/reference/setMBOControlTermination.html lists `time.budget` and `time.execution.budget` type both as `integer(1)`, but there is no reason why this should not be numeric, right?

**Comment by jakob-r** [comment]
Actually we store it as numeric because it supports `Inf`. So yes

**Comment by berndbischl** [comment]
just change it to numeric(1)

**Comment by mb706** [comment]
> Actually we store it as numeric because it supports `Inf`.

but otherwise fractional seconds are not supported?

**Comment by jakob-r** [comment]
They are. `difftime` returns fractions of seconds as well.
