### ISSUE TITLE
setMBOInfillCrit: not sure about parameter type

### ISSUE THREAD

**Issue by mb706** [mlr-org/mlrMBO#472]
> opt.ea.lambda | [numeric{1}]
For opt.ea = "ea". Number of children generated in each generation. Default is 1.

should this be an integer(1)?

**Comment by mb706** [comment]
same with opt.nsga2.{popsize,generations}

**Comment by berndbischl** [comment]
yes 2x

**Comment by jakob-r** [comment]
fixed in PR #479 . the assertions are already correct
