### ISSUE TITLE
Unable to install mlrMBO using install.packages dependencies=T. I am on IOS and using R v 1.4, someone else?

### ISSUE THREAD

**Issue by verofumero** [mlr-org/mlrMBO#511]

**Comment by verofumero** [comment]
> require("mlrMBO")
Loading required package: mlrMBO
Loading required package: mlr
Loading required package: ParamHelpers
Warning message: 'mlr' is in 'maintenance-only' mode since July 2019. Future development will
only happen in 'mlr3' (<https://mlr3.mlr-org.com>). Due to the focus on 'mlr3' there might be
uncaught bugs meanwhile in {mlr} - please consider switching.
Loading required package: smoof
Loading required package: checkmate

Attaching package: ‘checkmate’

The following object is masked from ‘package:DiceKriging’:

    checkNames


... and never stop!

**Comment by jakob-r** [comment]
Did you start from a clean r session? can you provide `sessionInfo()`?

**Comment by larskotthoff** [comment]
Can you also tell us what exactly you're trying to do please? The title suggests you're trying to install the package, but in the code snippet you're loading it.

**Comment by jakob-r** [comment]
Closed because no answer. Also... iOS???
