### ISSUE TITLE
optimizing "multiple objective" functions with "constraints"

### ISSUE THREAD

**Issue by swaheera** [mlr-org/mlrMBO#513]
https://cran.r-project.org/web/packages/mlrMBO/mlrMBO.pdf

Is it possible  to perform optimization on multi-objective functions with constraints? Or do these constraints need to be specified within the objective functions themselves?

Thanks

**Comment by jakob-r** [comment]
Can you specify which constraints you are thinking of?

**Comment by swaheera** [comment]
Hi Dr, Jakob,

Thank you for your reply - I will post an example.

Your Help is Greatly Appreciated
Thanks

**Comment by jakob-r** [comment]
Closed because you supplied examples in other issues
