### ISSUE TITLE
quickstart tutorial is not working

### ISSUE THREAD

**Issue by aydindemircioglu** [mlr-org/mlrMBO#52]
the quickstart tutorial does not seem to work on my system:
- there is no `generate_rastrigin_function` anymore in soobench,
  so the `obj.fun` must be changed to `rastrigin_function`
- `library(ParamHelpers)` needs to be included
- ParamHelpers needs to be installed from github, as mbo needs
  the `hasFiniteBoxConstraints`, which seems not to exist in
  the release version of paramhelpers
- the plot functions does not work (maybe thats me), i get
  `Error: number_of_parameters(x) == 2 is not TRUE`
  if i use `rastrigin_function(2)` it works, but i get a 2d graph.
- the quickstart talks about lhs design-- but i do not see that.
  is this happening somewhere inside the mbo functions?
- the code below that does not work, mbo tells me that
  Computing y column for design. Was not provided
  `Error in mapply(fun, ..., MoreArgs = more.args, SIMPLIFY = FALSE, USE.NAMES = FALSE) : 
  zero-length inputs cannot be mixed with those of non-zero length`
  am i missing something, doing something conceptionally wrong?

**Comment by aydindemircioglu** [comment]
is this really fixed? the tutorial still has

library(mlrMBO)
library(soobench)
objfun1 = generate_branin_function() # old soobench version: objfun1=branin_function()
## Error: konnte Funktion "generate_branin_function" nicht finden

and many more errors down the text.
needs only updating or fixing?

**Comment by jakobbossek** [comment]
The lines you mention above are part of the old quickstart tutorial. The [current version](https://github.com/berndbischl/mlrMBO/blob/master/doc/knitted/tutorial/quickstart.md) works well. Maybe you should delete your browser cache?

**Comment by aydindemircioglu** [comment]
sorry, i was a tad too unspecific, i was talking about the introduction.md file. 
(probably other places, too?)
https://github.com/berndbischl/mlrMBO/blob/master/doc/knitted/tutorial/introduction.md
thanks!

**Comment by jakobbossek** [comment]
Ok. Yes this is indeed not fixed yet. In the meanwhile we made many changes to the interface and especially the construction of the control object. Just open a new issue for that.
