### ISSUE TITLE
DiceKriging error (leading minor of order ...)

### ISSUE THREAD

**Issue by nbauer2** [mlr-org/mlrMBO#80]
``` r
objfun = generate_bbob2009_function(dimensions = 2, fid = 5, iid = 1L)
  opt = global_minimum(objfun)
  yopt = opt$value
  dim=2

  objfun2 = recording_function(objfun, record_pars = TRUE, record_values = TRUE)
    budget1 = dim * 5
    budget2 = dim * 40
    low = lower_bounds(objfun)
    upp = upper_bounds(objfun)
    par.set = makeNumericParamSet(len = dim, lower = low, upper = upp)
    initdes.x = generateDesign(budget1, par.set = par.set)
    initdes.y = apply(initdes.x, 1, objfun2)
    initdes = cbind(initdes.x, y = initdes.y)

  library(mlrMBO)


  ncores=5
  ea.maxit = 100L
    ea.sbx.p = 0.85
    ea.sbx.eta = 30
    ea.pm.p = 0.3
    ea.pm.eta = 30

  ctrl = makeMBOControl(
    iters = floor(budget2 / ncores),
    propose.points = ncores
  )

  ctrl = setMBOControlInfill(ctrl,
    crit = "lcb",
    opt = "ea",
    opt.restarts = 1L,
    opt.ea.maxit = ea.maxit * dim,
    opt.ea.mu = 5L,
    opt.ea.sbx.p = ea.sbx.p,
    opt.ea.sbx.eta = ea.sbx.eta,
    opt.ea.pm.p = ea.pm.p,
    opt.ea.pm.eta = ea.pm.eta
  )
  ctrl = setMBOControlMultiPoint(ctrl,
    method = "lcb"
  )

  lrn = makeLearner("regr.km", predict.type = "se", covtype = "matern3_2")

  m=mbo(makeMBOFunction(objfun), par.set = par.set,
    design = initdes, learner = lrn, control = ctrl)
```

I get:

```
[mbo] 1: x=4.61,5 : y = -8.82 : 0.0 secs
[mbo] 1: x=2.01,5 : y = -6.22 : 0.0 secs
[mbo] 2: x=5,5 : y = -9.21 : 0.0 secs
[mbo] 2: x=5,5 : y = -9.21 : 0.0 secs
[mbo] 2: x=3.68,5 : y = -7.89 : 0.0 secs
[mbo] 2: x=5,5 : y = -9.21 : 0.0 secs
[mbo] 3: x=5,5 : y = -9.21 : 0.0 secs
[mbo] 3: x=4.99,5 : y = -9.2 : 0.0 secs
[mbo] 4: x=4.73,5 : y = -8.94 : 0.0 secs
[mbo] 4: x=5,5 : y = -9.21 : 0.0 secs
[mbo] 4: x=5,5 : y = -9.21 : 0.0 secs
Warning in train(.learner$next.learner, .task) :
  Could not train learner regr.km: Error in chol.default(R) :
  the leading minor of order 21 is not positive definite

[mbo] 5: x=-0.0543,-2.05 : y = 66.4 : 0.0 secs
Error in addOptPathEl.OptPathDF(opt.path, x = x, y = y2, dob = dob, error.message = errmsg,  :
  Trying to add extra with different names!
In addition: Warning message:
In names(extra) == names(env$extra[[1L]]) :
  longer object length is not a multiple of shorter object length
```

**Comment by federicou** [comment]
I'm having the same problem with regr.km in mlr

Error in chol.default(R) : 
  the leading minor of order 165 is not positive definite

How have you managed to fix this out?

**Comment by berndbischl** [comment]
Thats basically not "our problem"  I think.
Its a numerical stability problem in DiceKriging / km. 

But mbo offers quite a lot of options to work around this and you I can try to guide you a bit here.

Questions 
Can you reproduce this?
What kernel are you using? 
Are you setting a nugget effect?
What infill are you using?
Check the print log. Are you adding (nearly) the same point twice during optimization?

**Comment by federicou** [comment]
Actually I've found a solution. It is true. It is not a problem related to mlr (or mlrMBO) itself but an issue related to the impossibility of inverting the covariance matrix.

As suggested in this [document](https://hal.inria.fr/hal-00495766v1/document) the solution is to set the proper number of nuggets as 

> To overcome
this difficulty, one can choose the diagonal inflation method:
> km(design=X, response=y, covtype="gauss", nugget=1e-8*var(y))

I've applied the following parameter setting:

```
y = MyTrainingData$MyTarget
Nuggets = 1e-8*var(y)
Learner <- setHyperPars(learner = Learner, par.vals = list(nugget=Nuggets)
```

I've kept the default covtype (matern5_2)

**Comment by berndbischl** [comment]
> itself but an issue related to the impossibility of inverting the covariance matrix.

exactly. it happens most often with the gaussian kernel, i think.

> I've applied the following parameter setting:

I do something similar very often. 

Conclusions:
a) We could add a note in the mlr learner.

b) for mbo we are working on better "entry points" into mlr with better defaults. this would be part of it.

c) Please also look at the option filter.propsed.points in makeMBOControlInfill. its not the smartest thing ever, but can also help with this problem. 

I usually use the nugget setting, like you posted, AND filter.proposed.points.

PS:

setHyperPars(learner = Learner, nugget=Nuggets)

is possible and shorter.

**Comment by berndbischl** [comment]
I guess I will add the note now and close then

**Comment by berndbischl** [comment]
@jakob-r 
should we introduce an option in mlr, to autoset nugget = 10-8 var(y) before training?

**Comment by jakob-r** [comment]
To be entirely correct we could set the nugget before each training. On the other hand I don't like to have so many DiceKriging dependent stuff in mlrMBO so what i think is more beautifuly would be a tiny wrapper for DiceKriging, so that in the end it would look like the following
```r
opt.fun = makeSingleObjectiveFunction(...)
ctrl = makeMboControl(...)
# ...
surrogate.learner = makeMboKrigingLearner(ctrl, opt.fun)
mbo(fun = opt.fun, design = des, learner = surrogate.learner, control = ctrl)
```

**Comment by jakob-r** [comment]
Closed. Continue in PR #223

**Comment by berndbischl** [comment]
> To be entirely correct we could set the nugget before each training.

**Comment by berndbischl** [comment]
> To be entirely correct we could set the nugget before each training.

please dont close issues before they are done. 
I suggested to do exactly to set the nugget before each training. but in mlr, so regr.km becomes more stable for all purposes. lets make this more explicit.

lrn = makeLearner("regr.km", mini.nugget = 1e-8)

and in the train function we simply do

if (mini.nugget != 0)
  nugget = mini.nugget * var(getTaskTarget(.task))

and throw an error if the user supllies nugget and mini.nugget. 

?

**Comment by berndbischl** [comment]
this seems IMHO the most "non-hacky" / most clean and general solution to the  problem?

**Comment by jakob-r** [comment]
I somehow dislike the idea of altering the behaviour of learners in mlr also I am happy that I can depend on the cran version of mlr.

**Comment by berndbischl** [comment]
> I somehow dislike the idea of altering the behaviour of learners in mlr

i know what you mean. but: we basically offer the user a mini-extra thing. which he only "gets" if he proactively requests this.

**Comment by jakob-r** [comment]
Se [this PR in mlr](https://github.com/mlr-org/mlr/pull/885) for the improved mlr learner

**Comment by mllg** [comment]
The mlr learner was merged. Can we close this? @berndbischl @jakob-r

**Comment by jakob-r** [comment]
Yes, we can.

**Comment by berndbischl** [comment]
agreed thx
