### ISSUE TITLE
we need final selection and final fevals for multicrit / noisy. 

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlrMBO#82]

**Comment by berndbischl** [comment]
do we even support the multicrit / noisy case?
I would say: no.

so we should simply check for this and throw an error now.

**Comment by danielhorn** [comment]
We don't have a method that is specially designed for a multicrit and noisy function. We could talk about parEGO and MSPOT using univariate noisy infill crits ... But I have no idea if and how good this would walk. 

I agree: For the moment don't allow noisy and multicrit at the same time. And look at it sometime in the (not so near) future.

**Comment by berndbischl** [comment]
Ok, then please add a "error check" in checkStuff with a PR and close this here.

**Comment by jakobbossek** [comment]
See PR #193
