### ISSUE TITLE
stochastic tests are bad

### ISSUE THREAD

**Issue by jakobbossek** [mlr-org/mlrMBO#90]
The unit test for `checkDesign` fails occasionally. We should handle this soon and check the other tests as well to keep the green travis button :-)

check design : .1...
1. Failure(@test_check_design.R#16): test checks for initial design and new design 
checkInitDesign(design2, par.set) isn't true

**Comment by berndbischl** [comment]
set seed only for cran

**Comment by berndbischl** [comment]
also i will look at the examples above

**Comment by mllg** [comment]
I'll fix this soon. We agreed to use a more robust version of `generateDesign` in the tests.

**Comment by mllg** [comment]
There is now a robust version of `generateDesign`. We still set a seed though...

**Comment by berndbischl** [comment]
so we are done here? your new design creation works for the unit tests and we have the cran seed?

**Comment by jakobbossek** [comment]
ping

**Comment by mllg** [comment]
`generateDesign` should be fixed now. We cannot set a seed **only** for CRAN. Therefore I set one if we are not on Travis.

**Comment by berndbischl** [comment]
> We cannot set a seed only for CRAN.

Totally OK what you did, but CRAN sets an envir var correct? Or do I misremember that?
I mean skip_on_cran works, so this must be possible?

**Comment by mllg** [comment]
> Totally OK what you did, but CRAN sets an envir var correct?

No.

**Comment by berndbischl** [comment]
Well.....
I did post a 2nd sentence for a reason.

```
> skip_on_cran
function () 
{
    if (identical(Sys.getenv("NOT_CRAN"), "true")) 
        return(invisible(TRUE))
    skip("On CRAN")
}
```

**Comment by berndbischl** [comment]
my suggestion is simply to use exactly THAT mechanism. because we already use it for skipping tests. out of a similar reason.

**Comment by mllg** [comment]
Have you set this envir variable? Or does travis?

**Comment by berndbischl** [comment]
i am currently looking at the devtools source code. I am not sure I understand it completely. 

Stuff that I know at the moment:
1) the dt docs basically seem to say: This envir var exists, it works to "detect cran".
2) from the code itself it dont understand how it works, except if cran would set NOT_CRAN = TRUE proactively on their system. NOT_CRAN = true is set as a default in dt code (not overwriting stuff set on the outside). but more I cannot see.
(and I know from discussions that cran didnt want to set these envir vars, but I might misremember or this changed)
3) For travis this is ensured that ir works, I have seen older, closed issues.
